<font color='#315aa0'>**Data Sets**</font>
---

## Índice

1. **Configuraciones**
   * Importación de librerías
   * Paths
   * Paletas de colores
2. **Exploración inicial**
   * Dataset Churn Bank
   * Dataset PaySim
3. **Manipulación de datos**
   * Churn
     - Fechas
     - Clusters Iniciales
     - Clusters K-Means
     - Interpretación Clusters K-Means
   * PaySim
     - Clasificación de transacciones
     - Asignación de transacciones
     - Limpieza datasets
     - Escalado del monto de las transacciones
4. **Salud del Dataset - Exploración**
   * Chequeos generales
   * Distribuciones numéricas
   * Churn
   * Correlación
5. **Filtrado**
6. **Guardado Datasets**

# <font color='#315aa0'>**Cofiguraciones**</font>

## <font color='#c37171'>**Importación de librerías**</font>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import kagglehub

import os
from pathlib import Path
from typing import Tuple, Callable, List

import warnings

warnings.filterwarnings('ignore')

## <font color='#c37171'>**Paths**</font>

In [2]:
# Obtiene el path actual
PROJECT_PATH = os.getcwd()

src = Path('src')
DATA_PATH = PROJECT_PATH / src

img = Path('img')
IMG_PATH = PROJECT_PATH / img

models = Path('models')
MODELS_PATH = PROJECT_PATH / models

reports = Path('reports')
REPORTS_PATH = PROJECT_PATH / reports

dirs = [DATA_PATH, IMG_PATH, MODELS_PATH, REPORTS_PATH]


for directory in dirs:
    if not directory.exists():
        directory.mkdir(parents=True)
        print(f'Directorio creado:\n{directory}\n')
    else:
        print(f'El directorio ya existe:\n{directory}\n')

El directorio ya existe:
C:\Users\Ignacio\JupyterScripts\Fintech_NC\src

El directorio ya existe:
C:\Users\Ignacio\JupyterScripts\Fintech_NC\img

El directorio ya existe:
C:\Users\Ignacio\JupyterScripts\Fintech_NC\models

El directorio ya existe:
C:\Users\Ignacio\JupyterScripts\Fintech_NC\reports



## <font color='#c37171'>**Paleta de Colores del Proyecto**</font>


**Bordós / Rojos**

<span style="display:inline-block; width:20px; height:20px; background:#620c0c; margin-right:5px;"></span> 
<span style="display:inline-block; width:20px; height:20px; background:#8b1f1f; margin-right:5px;"></span> 
<span style="display:inline-block; width:20px; height:20px; background:#a14b4b; margin-right:5px;"></span> 
<span style="display:inline-block; width:20px; height:20px; background:#c37171; margin-right:5px;"></span> 
<span style="display:inline-block; width:20px; height:20px; background:#e29c9c; margin-right:5px;"></span>

**Grises / Neutros**

<span style="display:inline-block; width:20px; height:20px; background:#5a5858; margin-right:5px;"></span> 
<span style="display:inline-block; width:20px; height:20px; background:#8c8a8a; margin-right:5px;"></span> 
<span style="display:inline-block; width:20px; height:20px; background:#b0aeae; margin-right:5px;"></span> 
<span style="display:inline-block; width:20px; height:20px; background:#d3d1d1; margin-right:5px;"></span> 
<span style="display:inline-block; width:20px; height:20px; background:#eae7e6; margin-right:5px;"></span>

**Azules**

<span style="display:inline-block; width:20px; height:20px; background:#0d1b3d; margin-right:5px;"></span> 
<span style="display:inline-block; width:20px; height:20px; background:#152a55; margin-right:5px;"></span> 
<span style="display:inline-block; width:20px; height:20px; background:#1e3a6c; margin-right:5px;"></span> 
<span style="display:inline-block; width:20px; height:20px; background:#274a84; margin-right:5px;"></span> 
<span style="display:inline-block; width:20px; height:20px; background:#315aa0; margin-right:5px;"></span>

**Cremas / Mostazas**

<span style="display:inline-block; width:20px; height:20px; background:#FCB53B; margin-right:5px;"></span> 
<span style="display:inline-block; width:20px; height:20px; background:#FDB860; margin-right:5px;"></span> 
<span style="display:inline-block; width:20px; height:20px; background:#FDC584; margin-right:5px;"></span> 
<span style="display:inline-block; width:20px; height:20px; background:#FDD2A9; margin-right:5px;"></span> 
<span style="display:inline-block; width:20px; height:20px; background:#FDE0CE; margin-right:5px;"></span>

In [3]:
BORDO_1, BORDO_2, BORDO_3, BORDO_4, BORDO_5 = '#620c0c', '#8b1f1f', '#a14b4b', '#c37171', '#e29c9c' 
GRIS_1, GRIS_2, GRIS_3, GRIS_4, GRIS_5 = '#5a5858', '#8c8a8a', '#b0aeae', '#d3d1d1', '#eae7e6' 
AZUL_1, AZUL_2, AZUL_3, AZUL_4, AZUL_5 = '#0d1b3d', '#152a55', '#1e3a6c', '#274a84', '#315aa0' 
CREMA_1, CREMA_2, CREMA_3, CREMA_4, CREMA_5 = '#FCB53B', '#FDB860', '#FDC584', '#FDD2A9', '#FDE0CE'

# <font color='#315aa0'>**Exploración inicial**</font>

## <font color='#c37171'>**Dataset Churn Bank**</font>

In [4]:
df_churn = pd.read_csv(DATA_PATH/'churn.csv')
df_churn.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
df_churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [6]:
df_churn.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [7]:
df_churn['Exited'].sum()

2037

In [8]:
df_churn['Exited'].value_counts(normalize=True)

Exited
0    0.7963
1    0.2037
Name: proportion, dtype: float64

In [9]:
df_churn['CustomerId'].nunique()

10000

## <font color='#c37171'>**Dataset PaySim**</font>

In [10]:
path_paysim = kagglehub.dataset_download('ealaxi/paysim1')

print('Path to dataset PaySim:', path_paysim)

Path to dataset PaySim: C:\Users\Ignacio\.cache\kagglehub\datasets\ealaxi\paysim1\versions\2


In [11]:
paysim_file = Path('PS_20174392719_1491204439457_log.csv')
df_paysim = pd.read_csv(path_paysim / paysim_file)
df_paysim.head()

step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36   
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72   
2     1  TRANSFER    181.00  C1305486145          181.0            0.00   
3     1  CASH_OUT    181.00   C840083671          181.0            0.00   
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0  M1979787155             0.0             0.0        0               0  
1  M2044282225             0.0             0.0        0               0  
2   C553264065             0.0             0.0        1               0  
3    C38997010         21182.0             0.0        1               0  
4  M1230701703             0.0             0.0        0               0

In [12]:
df_paysim.shape

(6362620, 11)

In [13]:
df_paysim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype  
---  ------          -----  
 0   step            int64  
 1   type            object 
 2   amount          float64
 3   nameOrig        object 
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object 
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64  
 10  isFlaggedFraud  int64  
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB


In [14]:
df_paysim.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [15]:
df_paysim.describe()

step        amount  oldbalanceOrg  newbalanceOrig  \
count  6.362620e+06  6.362620e+06   6.362620e+06    6.362620e+06   
mean   2.433972e+02  1.798619e+05   8.338831e+05    8.551137e+05   
std    1.423320e+02  6.038582e+05   2.888243e+06    2.924049e+06   
min    1.000000e+00  0.000000e+00   0.000000e+00    0.000000e+00   
25%    1.560000e+02  1.338957e+04   0.000000e+00    0.000000e+00   
50%    2.390000e+02  7.487194e+04   1.420800e+04    0.000000e+00   
75%    3.350000e+02  2.087215e+05   1.073152e+05    1.442584e+05   
max    7.430000e+02  9.244552e+07   5.958504e+07    4.958504e+07   

       oldbalanceDest  newbalanceDest       isFraud  isFlaggedFraud  
count    6.362620e+06    6.362620e+06  6.362620e+06    6.362620e+06  
mean     1.100702e+06    1.224996e+06  1.290820e-03    2.514687e-06  
std      3.399180e+06    3.674129e+06  3.590480e-02    1.585775e-03  
min      0.000000e+00    0.000000e+00  0.000000e+00    0.000000e+00  
25%      0.000000e+00    0.000000e+00  0.000000e+00    0.000000e+00  
50%      1.327057e+05    2.146614e+05  0.000000e+00    0.000000e+00  
75%      9.430367e+05    1.111909e+06  0.000000e+00    0.000000e+00  
max      3.560159e+08    3.561793e+08  1.000000e+00    1.000000e+00

In [16]:
df_paysim['type'].unique()

array(['PAYMENT', 'TRANSFER', 'CASH_OUT', 'DEBIT', 'CASH_IN'],
      dtype=object)

In [17]:
df_paysim['type'].value_counts(normalize=True)

type
CASH_OUT    0.351663
PAYMENT     0.338146
CASH_IN     0.219923
TRANSFER    0.083756
DEBIT       0.006512
Name: proportion, dtype: float64

In [18]:
df_paysim['amount'].max()

92445516.64

In [19]:
df_churn['EstimatedSalary'].max()

199992.48

In [20]:
len(df_paysim) / df_churn['CustomerId'].nunique()

636.262

## <font color='#FCB53B'>**Observaciones iniciales**</font>

### <font color='#c37171'>**DataFrame PaySim (Simluación Transacciones Bancarias)**</font>

* **Cantidad transacciones:** 6 362 620

* **Max Transaction amount:** 92 445 516.64

### <font color='#c37171'>**DataFrame Churn**</font>

* **Clientes unicos:** 10 000
  
* **Clientes Churn = Yes:** 2037 *(20% aprox)*

* **Max balance**: 250 898.09
* **Max estimated salary**: 199 992.48

### **Problemas iniciales**

El primer problema surge por supuesto porque los Ids no son los mismos, ya que no corresponden al mismo dataset. Uno cuenta con 10000 ids unicos (df_churn), el otro cuenta con 6353307 ids unicos (casi la misma cantidad de transacciones).

Otro problema que surge es que los montos son muy distintos entre ambos datasets. Se puede ver en el monto maximo de transaccion de PaySim y el balance maximo de Churn Otra cosa es que el step es de una hora, cuenta con 743 (correspondiente a un mes) cuando el tenure en el df_churn está medido en años, esto habrá que modificarlo de alguna manera.
<br>
### **Ideas iniciales**
<br>

> **TRANSACCIONES**

* Quedarme con todas las transacciones. Pero como el objetivo del problema es churn, no me interesan varias columnas. 

Consevaría:

**step:** lo transformaría en fechas en un rango quizás de 2 años ya que hay 743 steps<br>
**type:** tipo de transacciones<br>
**amount:** necesita ser reescalado, y las transacciones no pueden ser nunca mayores al saldo de la cuenta<br>
**nameOrig:** reemplazar por IDs de df_churn<br>

Estas dos no estoy seguro todavía:

**oldbalanceOrg**<br>
**newbalanceOrig**

<br>

> **IDs**

* Utilizar los IDs de **df_churn**, y buscar la manera de asignarlos de manera aleatoria a las transacciones. Esto deberá seguir cierta lógica ya que los clientes que se fueron no deberían tener transacciones en los últimos X meses.
Esto deberá respetar una logica donde se agrupen los clientes que tienen `Exited = 1` y que vaya variando, debe haber clientes con distintas fechas de abandono, entre 6 y 0 meses.

# <font color='#315aa0'>**Manipulación de datos**</font>

## 🔑 <font color='#c37171'>**Principios para evitar “dataset basura”**</font>
---

### 1. Definir hipótesis de negocio realistas

Antes de tocar los datos, escribir supuestos que tengan sentido en un banco real:

- Clientes con menos interacciones en la app = más probabilidad de churn.
- Disminución en frecuencia de transacciones en los últimos meses = mayor riesgo de churn.
- Edad y salario influyen en la estabilidad del cliente (jóvenes y bajos salarios = más churn).
- Factores externos como inflación alta → más churn en clientes de bajo ingreso.

> 👉 Esto asegura que los patrones que generes no sean aleatorios, sino consistentes con lo que podría pasar en la realidad.

---

### 2. Usar correlaciones en lugar de ruido puro
En lugar de asignar variables externas o de interacción al azar:

- Introducir variables que estén correlacionadas con churn de forma controlada.

**Ejemplo:**
- Clientes que hicieron churn tienen un 40% menos de interacciones con la app en los últimos 3 meses.
- Clientes de churn tienen un 20% más de transacciones fallidas o rechazadas.
- Factores externos (ej: inflación simulada) afectan más a clientes con Balance < X.

> 👉 Esto genera señales diferenciales para el modelo.

---

### 3. Introducir variabilidad dentro de cada grupo

No todos los clientes que hicieron churn deben tener baja actividad. Introducir distribuciones:

- 60% de churners tienen muy baja interacción.
- 30% tienen actividad media.
- 10% siguen siendo activos hasta el final.

> 👉 Esto evita que el modelo aprenda reglas triviales (del tipo: “si transacciones = 0 → churn”).

---

### 4. Usar ruido controlado (stochastic noise)
Un poco de azar es necesario para que no todo sea determinístico, pero debe ser pequeño en comparación con la señal principal.

**Ejemplo:**  
Número de interacciones promedio de un churner = 20, con desviación estándar de ±5.

---

### 5. Validación manual antes del modelo
Antes de entrenar, explorar el dataset final con gráficos:

- Histograma de transacciones churn vs no churn.
- Interacciones app churn vs no churn.
- Factores externos según balance.

> 👉 Si se ven diferencias razonables entre grupos, entonces el dataset tiene patrones útiles.

---

## 🔧 <font color='#c37171'>**Overview de los 4 datasets**</font>

### 1. Churn (base)
- Target + atributos estáticos.

### 2. Transacciones
- Clientes que hicieron churn deben mostrar una caída de actividad en los últimos meses.
- Clientes que no hicieron churn mantienen o aumentan su actividad.

### 3. Interacciones con la app
- Churners: menor login, menor tiempo en app, menos clicks en productos financieros.
- No churners: más consistencia en el uso.

### 4. Factores externos
- Podés simular inflación, tasa de interés, etc.
- Definí reglas: clientes de menor salario son más sensibles = más probabilidad de churn cuando inflación sube.

## <font color='#c37171'>**Churn**</font>

In [21]:
df_churn_man = df_churn.copy()

### <font color='#FCB53B'>**Fechas**</font>

In [22]:
periods = df_paysim['step'].nunique()
periods

743

In [23]:
end_date = pd.to_datetime('2025-09-30')
end_date

Timestamp('2025-09-30 00:00:00')

In [24]:
start_date = end_date - pd.Timedelta(days=periods-1)
start_date

Timestamp('2023-09-19 00:00:00')

In [25]:
fechas = pd.date_range(start=start_date, periods=periods, freq="D")

print(fechas)

DatetimeIndex(['2023-09-19', '2023-09-20', '2023-09-21', '2023-09-22',
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28',
               ...
               '2025-09-21', '2025-09-22', '2025-09-23', '2025-09-24',
               '2025-09-25', '2025-09-26', '2025-09-27', '2025-09-28',
               '2025-09-29', '2025-09-30'],
              dtype='datetime64[ns]', length=743, freq='D')


In [26]:
enum = [i for i in range(1, 744)]

In [27]:
df_fechas = pd.DataFrame({'step': enum, 'fecha': fechas})
df_fechas

step      fecha
0       1 2023-09-19
1       2 2023-09-20
2       3 2023-09-21
3       4 2023-09-22
4       5 2023-09-23
..    ...        ...
738   739 2025-09-26
739   740 2025-09-27
740   741 2025-09-28
741   742 2025-09-29
742   743 2025-09-30

[743 rows x 2 columns]

In [28]:
df_fechas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 743 entries, 0 to 742
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   step    743 non-null    int64         
 1   fecha   743 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(1)
memory usage: 11.7 KB


In [29]:
fechas_abandono = fechas[int((len(fechas)/4 * 3)):]
fechas_abandono

DatetimeIndex(['2025-03-29', '2025-03-30', '2025-03-31', '2025-04-01',
               '2025-04-02', '2025-04-03', '2025-04-04', '2025-04-05',
               '2025-04-06', '2025-04-07',
               ...
               '2025-09-21', '2025-09-22', '2025-09-23', '2025-09-24',
               '2025-09-25', '2025-09-26', '2025-09-27', '2025-09-28',
               '2025-09-29', '2025-09-30'],
              dtype='datetime64[ns]', length=186, freq='D')

In [30]:
len(fechas_abandono)

186

In [31]:
import random

abandono_cust = []

for exited in df_churn_man['Exited']:
    if exited == 1:
        if random.random() < 0.75:
            # 75% de churners en los últimos 6 meses
            rand_idx = int(np.random.triangular(0, len(fechas_abandono)-1, len(fechas_abandono)-1))
            abandono_cust.append(fechas_abandono[rand_idx])
        else:
            # 25 % churners en cualquier fecha del período
            abandono_cust.append(random.choice(fechas))
    else:
        abandono_cust.append(np.nan)

In [32]:
df_churn_man['ExitDate'] = abandono_cust

In [33]:
df_churn_man.sample(5)

RowNumber  CustomerId        Surname  CreditScore Geography  Gender  \
3674       3675    15749693  Ugonnatubelum          658    France  Female   
8827       8828    15580149         Fowler          638     Spain    Male   
1388       1389    15775295       McIntyre          630    France  Female   
6478       6479    15573348        Maclean          850    France    Male   
3916       3917    15620276        Palermo          539     Spain    Male   

      Age  Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
3674   32       9       0.00              2          1               0   
8827   41       7       0.00              2          1               0   
1388   40       0  118633.08              1          0               1   
6478   35       9  102050.47              1          1               1   
3916   36       6       0.00              3          1               1   

      EstimatedSalary  Exited   ExitDate  
3674        156774.75       0        NaT  
8827         43889.41       0        NaT  
1388         60032.46       1 2025-05-02  
6478          3769.71       0        NaT  
3916        118959.64       0        NaT

### <font color='#FCB53B'>**Clusteres iniciales**</font>

Se asignarán scores de acuerdo a distintos aspectos del cliente:

* Tiempo: Edad y Antigüedad
* Riqueza: Balance, Salario Estimado y Puntaje Crediticio
* Compromiso: Número de productos, si Cuenta con Tarjeta de Crédito y si es Miembro Activo

Esto permitirá asignar un puntaje a cada cliente referente a cada aspecto, esto se utilizará luego para realizar una clusterización, y usar los clusters para asignar posteriormente las transacciones e interacciones con la app.

In [34]:
df_clusters = df_churn_man.copy()

In [35]:
df_clusters['cluster_time'] = pd.qcut(df_clusters['Tenure']*0.6 + df_clusters['Age']*0.4, q=3, labels=['Low','Medium','High'])

In [36]:
df_clusters['wealth_score'] = df_clusters['Balance']*0.5 + df_clusters['EstimatedSalary']*0.4 + df_clusters['CreditScore']*0.1
df_clusters['cluster_wealth'] = pd.qcut(df_clusters['wealth_score'], q=3, labels=['Low','Medium','High'])

In [37]:
df_clusters['engagement_score'] = df_clusters['NumOfProducts']*0.5 + df_clusters['HasCrCard']*0.2 + df_clusters['IsActiveMember']*0.3
df_clusters['cluster_engagement'] = pd.qcut(df_clusters['engagement_score'], q=3, labels=['Low','Medium','High'])

In [38]:
df_clusters

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited   ExitDate cluster_time  wealth_score  \
0           101348.88       1 2025-02-26       Medium     40601.452   
1           112542.58       0        NaT       Medium     86981.762   
2           113931.57       1 2024-07-23         High    125453.228   
3            93826.63       0        NaT          Low     37600.552   
4            79084.10       0        NaT       Medium     94474.050   
...               ...     ...        ...          ...           ...   
9995         96270.64       0        NaT       Medium     38585.356   
9996        101699.77       0        NaT         High     69416.313   
9997         42085.58       1 2025-05-16       Medium     16905.132   
9998         92888.52       1 2024-09-07       Medium     74770.263   
9999         38190.78       0        NaT          Low     80426.907   

     cluster_wealth  engagement_score cluster_engagement  
0               Low               1.0                Low  
1            Medium               0.8                Low  
2              High               1.7               High  
3               Low               1.0                Low  
4            Medium               1.0                Low  
...             ...               ...                ...  
9995            Low               1.2             Medium  
9996         Medium               1.0                Low  
9997            Low               0.8                Low  
9998         Medium               1.2             Medium  
9999         Medium               0.7                Low  

[10000 rows x 20 columns]

### <font color='#FCB53B'>**Clusters K-Means**</font>

In [39]:
# Normalizar los scores para que estén en la misma escala
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df_clusters[['wealth_score_norm', 'engagement_score_norm']] = scaler.fit_transform(df_clusters[['wealth_score', 'engagement_score']])

time_mapping = {'Low': 0, 'Medium': 0.5, 'High': 1}
df_clusters['cluster_time_num'] = df_clusters['cluster_time'].map(time_mapping).astype(float)

df_clusters.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  ...  Exited   ExitDate  cluster_time  \
0       2       0.00              1  ...       1 2025-02-26        Medium   
1       1   83807.86              1  ...       0        NaT        Medium   
2       8  159660.80              3  ...       1 2024-07-23          High   
3       1       0.00              2  ...       0        NaT           Low   
4       2  125510.82              1  ...       0        NaT        Medium   

   wealth_score cluster_wealth engagement_score  cluster_engagement  \
0     40601.452            Low              1.0                 Low   
1     86981.762         Medium              0.8                 Low   
2    125453.228           High              1.7                High   
3     37600.552            Low              1.0                 Low   
4     94474.050         Medium              1.0                 Low   

  wealth_score_norm  engagement_score_norm cluster_time_num  
0          0.220009                   0.25              0.5  
1          0.471943                   0.15              0.5  
2          0.680918                   0.60              1.0  
3          0.203708                   0.25              0.0  
4          0.512641                   0.25              0.5  

[5 rows x 23 columns]

In [40]:
df_clusters.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'ExitDate',
       'cluster_time', 'wealth_score', 'cluster_wealth', 'engagement_score',
       'cluster_engagement', 'wealth_score_norm', 'engagement_score_norm',
       'cluster_time_num'],
      dtype='object')

In [41]:
df_clusters['final_score'] = 0.4*df_clusters['wealth_score_norm'] + 0.4*df_clusters['engagement_score_norm'] + 0.2*df_clusters['cluster_time_num']

In [42]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=5, random_state=42)
df_clusters['cluster_final'] = kmeans.fit_predict(df_clusters[['final_score']])

In [43]:
df_clusters

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  ...  cluster_time  wealth_score  \
0          2       0.00              1  ...        Medium     40601.452   
1          1   83807.86              1  ...        Medium     86981.762   
2          8  159660.80              3  ...          High    125453.228   
3          1       0.00              2  ...           Low     37600.552   
4          2  125510.82              1  ...        Medium     94474.050   
...      ...        ...            ...  ...           ...           ...   
9995       5       0.00              2  ...        Medium     38585.356   
9996      10   57369.61              1  ...          High     69416.313   
9997       7       0.00              1  ...        Medium     16905.132   
9998       3   75075.31              2  ...        Medium     74770.263   
9999       4  130142.79              1  ...           Low     80426.907   

      cluster_wealth  engagement_score cluster_engagement wealth_score_norm  \
0                Low               1.0                Low          0.220009   
1             Medium               0.8                Low          0.471943   
2               High               1.7               High          0.680918   
3                Low               1.0                Low          0.203708   
4             Medium               1.0                Low          0.512641   
...              ...               ...                ...               ...   
9995             Low               1.2             Medium          0.209058   
9996          Medium               1.0                Low          0.376529   
9997             Low               0.8                Low          0.091292   
9998          Medium               1.2             Medium          0.405611   
9999          Medium               0.7                Low          0.436338   

      engagement_score_norm cluster_time_num  final_score cluster_final  
0                      0.25              0.5     0.288004             2  
1                      0.15              0.5     0.348777             4  
2                      0.60              1.0     0.712367             3  
3                      0.25              0.0     0.181483             1  
4                      0.25              0.5     0.405056             4  
...                     ...              ...          ...           ...  
9995                   0.35              0.5     0.323623             2  
9996                   0.25              1.0     0.450612             0  
9997                   0.15              0.5     0.196517             1  
9998                   0.35              0.5     0.402245             4  
9999                   0.10              0.0     0.214535             1  

[10000 rows x 25 columns]

### <font color='#FCB53B'>**Interpretación clusters K-Means**</font>

In [44]:
clusters_count = df_clusters['cluster_final'].value_counts()
clusters_count

cluster_final
4    2874
2    2646
0    2230
1    1434
3     816
Name: count, dtype: int64

In [45]:
df_clusters_count = pd.DataFrame({'index':clusters_count.index, 'count': clusters_count})

In [46]:
df_clusters_count

index  count
cluster_final              
4                  4   2874
2                  2   2646
0                  0   2230
1                  1   1434
3                  3    816

In [47]:
centroids_clusters_kmeans = kmeans.cluster_centers_
df_centroides = pd.DataFrame(centroids_clusters_kmeans, columns=['final_score'])
df_centroides.reset_index(inplace=True)

In [48]:
df_centroides

index  final_score
0      0     0.494466
1      1     0.191013
2      2     0.299533
3      3     0.624389
4      4     0.395506

In [49]:
df_centroides = df_centroides.merge(df_clusters_count, on='index')
df_centroides = df_centroides.rename(columns={'index': 'cluster'})

In [50]:
df_centroides.sort_values('final_score')

cluster  final_score  count
1        1     0.191013   1434
2        2     0.299533   2646
4        4     0.395506   2874
0        0     0.494466   2230
3        3     0.624389    816

In [51]:
def proporcion_labels(df):
    """
    Esta función tomará un df que debe corresponder a un unico cluster y
    retornará las proporciones de cada etiqueta de los clusters utilizados inicialmente
    """
    
    cluster_labels = ['cluster_time', 'cluster_wealth', 'cluster_engagement']
    counts = {}

    for cluster in cluster_labels:
        counts[cluster] = df[cluster].value_counts(normalize=True)

    return pd.DataFrame(counts)

#### <font color='#FDD2A9'>**Cluster 0**</font>

In [52]:
cluster_0 = df_clusters[df_clusters['cluster_final'] == 0]
prop_cluster_0 = proporcion_labels(cluster_0)
prop_cluster_0

cluster_time  cluster_wealth  cluster_engagement
Low         0.070852        0.123318            0.503139
Medium      0.311211        0.343049            0.134978
High        0.617937        0.533632            0.361883

#### <font color='#FDD2A9'>**Observaciones Cluster 0:**</font>


Los clientes del **Cluster 0** cuentan con las siguientes características:
* Cuenta con un **score general** de: **0.494466** (2do más alto en el ranking)
* **Cantidad de clientes** pertenencientes al cluster: **2230 clientes**
* *cluster_time:* 60% para clientes con un alto score de tiempo (edad y permanencia) y 30% para término medio.
* *cluster_wealth:* 50% concentrado en clientes con buena salud económica, 35% para término medio.
* *cluster_engagement:* 50% con poco engagement, 35% con alto engagement.

Este es un buen perfil de cliente, ya que son clientes antiguos y con buen poder adquisitivo

#### <font color='#FDD2A9'>**Cluster 1**</font>

In [53]:
cluster_1 = df_clusters[df_clusters['cluster_final'] == 1]
prop_cluster_1 = proporcion_labels(cluster_1)
prop_cluster_1

cluster_time  cluster_wealth  cluster_engagement
Low          0.82636        0.734310            0.722455
Medium       0.16318        0.243375            0.156206
High         0.01046        0.022315            0.121339

#### <font color='#FDD2A9'>**Observaciones Cluster 1:**</font>

Los clientes del **Cluster 1** cuentan con las siguientes características:

* Cuenta con un **score general** de: **0.191013** (ranking más bajo)
* **Cantidad de clientes** pertenencientes al cluster: **1434 clientes**
* *cluster_time:* 82% para clientes con un bajo score de tiempo (edad y permanencia) y 16% para término medio.
* *cluster_wealth:* 73% concentrado en clientes con baja salud económica, 24% para término medio.
* *cluster_engagement:* 72% con poco engagement, 12% con engagement término medio y 12% con alto engagement.

Este es el perfi de cliente con menor valor para la empresa, son clientes nuevos, de bajo poder adquisitivo, y con poco compromiso

#### <font color='#FDD2A9'>**Cluster 2**</font>

In [54]:
cluster_2 = df_clusters[df_clusters['cluster_final'] == 2]
prop_cluster_2 = proporcion_labels(cluster_2)
prop_cluster_2

cluster_time  cluster_wealth  cluster_engagement
Low         0.522298        0.432729            0.642857
Medium      0.387755        0.365835            0.167800
High        0.089947        0.201436            0.189342

#### <font color='#FDD2A9'>**Observaciones Cluster 2:**</font>

Los clientes del **Cluster 2** cuentan con las siguientes características:

* Cuenta con un **score general** de: **0.299533**
* **Cantidad de clientes** pertenencientes al cluster: **2646 clientes**
* *cluster_time:* 52% para clientes con un bajo score de tiempo (edad y permanencia) y 38% para término medio.
* *cluster_wealth:* 20% concentrado en clientes con buena salud económica, 36% para término medio, y 43% para baja riqueza.
* *cluster_engagement:* 64% con poco engagement, 16% con engagement término medio y 19% con alto engagement.

Este es el perfi de cliente tiene poco compromiso, pero con potencial para fidelizar, ya que la riqueza esta distribuida de forma relativamente pareja, y son clientes nuevos y/o jovenes.

#### <font color='#FDD2A9'>**Cluster 3**</font>

In [55]:
cluster_3 = df_clusters[df_clusters['cluster_final'] == 3]
prop_cluster_3 = proporcion_labels(cluster_3)
prop_cluster_3

cluster_time  cluster_wealth  cluster_engagement
Low         0.009804        0.030637            0.215686
Medium      0.151961        0.197304            0.123775
High        0.838235        0.772059            0.660539

#### <font color='#FDD2A9'>**Observaciones Cluster 3:**</font>

Los clientes del **Cluster 3** cuentan con las siguientes características:
	
* Cuenta con un **score general** de: **0.624389** (ranking más alto)
* **Cantidad de clientes** pertenencientes al cluster: **816 clientes** (cluster más pequeño)
* *cluster_time:* 83% para clientes con un alto score de tiempo (edad y permanencia) y 15% para término medio.
* *cluster_wealth:* 77% concentrado en clientes con buena salud económica, 19% para término medio, y 3% para baja riqueza.
* *cluster_engagement:* 66% con alto engagement, 12% con engagement término medio y 21% con bajo engagement.

Este es el perfil de cliente **"VIP"**. Son clientes antiguos y con muy buena salud económica (posiblemente también sean los clientes más adultos). Y con buen nivel de compromiso.

#### <font color='#FDD2A9'>**Cluster 4**</font>

In [56]:
cluster_4 = df_clusters[df_clusters['cluster_final'] == 4]
prop_cluster_4 = proporcion_labels(cluster_4)
prop_cluster_4

cluster_time  cluster_wealth  cluster_engagement
Low         0.218163        0.290536            0.585247
Medium      0.452679        0.379610            0.153445
High        0.329158        0.329854            0.261308

#### <font color='#FDD2A9'>**Observaciones Cluster 4:**</font>

Los clientes del **Cluster 4** cuentan con las siguientes características:
	
* Cuenta con un **score general** de: **0.395506**
* **Cantidad de clientes** pertenencientes al cluster: **2874 clientes** (cluster más grande)
* *cluster_time:* 32% para clientes con un alto score de tiempo (edad y permanencia) y 45% para término medio y 21% de bajo score de tiempo.
* *cluster_wealth:* 32% de clientes con buena salud económica, 37% para término medio, y 29% para baja riqueza.
* *cluster_engagement:* 26% con alto engagement, 15% con engagement término medio y 58% con bajo engagement.

Este es el perfil de cliente **"Standard"**. Son clientes ni muy antiguos ni muy nuevos, ni muy ricos ni muy pobres, predomina un compromiso bajo.

In [57]:
etiquetas = {0: 'Valioso - Bajo compromiso',
             1: 'Nuevos - Poco Valor',
             2: 'Clientes potenciales',
             3: 'VIP',
             4: 'Standard'}

In [58]:
df_clusters['cluster_label'] = df_clusters['cluster_final'].map(etiquetas)

In [59]:
df_clusters.sample(20)

RowNumber  CustomerId      Surname  CreditScore Geography  Gender  Age  \
9443       9444    15687001    Chiemenam          596   Germany    Male   54   
2653       2654    15785078        Fomin          730     Spain    Male   26   
9483       9484    15675983         Wood          692    France  Female   36   
2447       2448    15715769          Hao          621    France    Male   26   
8092       8093    15663770        Doyle          802    France    Male   38   
5703       5704    15621063      Gibbons          516    France  Female   42   
7473       7474    15638272         Tien          609     Spain    Male   32   
7383       7384    15672912       Loggia          737     Spain  Female   39   
4542       4543    15585455      Stewart          630    France    Male   28   
1668       1669    15755722           H?          554    France    Male   24   
7052       7053    15681755       Dennys          605    France  Female   32   
3448       3449    15610903  Chukwueloka          560     Spain  Female   31   
7263       7264    15622729          Sun          649    France  Female   46   
9350       9351    15689344   Montgomery          615     Spain    Male   42   
592         593    15679587         Chan          666    France  Female   34   
1560       1561    15634281         P'an          720   Germany  Female   43   
4777       4778    15619801        Batty          548    France  Female   33   
3545       3546    15690130        Wyatt          468    France  Female   32   
4266       4267    15673984      Daniels          536    France  Female   35   
5948       5949    15680112      Stewart          473   Germany  Female   35   

      Tenure    Balance  NumOfProducts  ...  wealth_score  cluster_wealth  \
9443       1  123544.00              1  ...    109957.500            High   
2653       3       0.00              1  ...     13889.964             Low   
9483       3   79551.12              1  ...    111151.588            High   
2447       2   75237.54              1  ...     55369.030             Low   
8092       1  142557.11              1  ...    140357.847            High   
5703       8   56228.25              1  ...     46908.733             Low   
7473       4   99883.16              1  ...     98240.420            High   
7383       7  130051.66              2  ...     87242.086          Medium   
4542       9       0.00              2  ...     13102.740             Low   
1668      10       0.00              1  ...     36927.648             Low   
7052       5       0.00              2  ...     16914.612             Low   
3448       5  125341.69              1  ...     94545.801          Medium   
7263       2       0.00              2  ...     26705.980             Low   
9350       4       0.00              3  ...     48189.936             Low   
592        9  115897.12              1  ...     68053.172          Medium   
1560      10  110822.90              1  ...     84628.226          Medium   
4777       1   80107.83              2  ...     73006.983          Medium   
3545       8  137649.47              1  ...    148357.251            High   
4266       8       0.00              1  ...     68789.696          Medium   
5948       7  131504.73              1  ...    141623.837            High   

      engagement_score  cluster_engagement wealth_score_norm  \
9443               1.0                 Low          0.596746   
2653               0.7                 Low          0.074914   
9483               0.8                 Low          0.603232   
2447               0.8                 Low          0.300225   
8092               1.0                 Low          0.761878   
5703               0.7                 Low          0.254270   
7473               1.0                 Low          0.533100   
7383               1.0                 Low          0.473357   
4542               1.0                 Low          0.070638   
1668               0.5                 Low          0.200053   
705

In [60]:
df_churn_labeled = df_clusters.copy()

In [61]:
df_churn_labeled.groupby('cluster_label')['cluster_label'].value_counts()

cluster_label
Clientes potenciales         2646
Nuevos - Poco Valor          1434
Standard                     2874
VIP                           816
Valioso - Bajo compromiso    2230
Name: count, dtype: int64

In [62]:
df_churn_labeled['cluster_label'].value_counts(normalize=True)

cluster_label
Standard                     0.2874
Clientes potenciales         0.2646
Valioso - Bajo compromiso    0.2230
Nuevos - Poco Valor          0.1434
VIP                          0.0816
Name: proportion, dtype: float64

In [63]:
churn_yes = df_churn_labeled[df_churn_labeled['Exited'] == 1]
churn_yes.groupby('cluster_label')['cluster_label'].value_counts()

cluster_label
Clientes potenciales         380
Nuevos - Poco Valor          178
Standard                     590
VIP                          329
Valioso - Bajo compromiso    560
Name: count, dtype: int64

## <font color='#c37171'>**PaySim**</font>

In [64]:
df_paysim_man = df_paysim.copy()

In [65]:
fechas_paysim = df_fechas.copy()

In [66]:
df_paysim_man = df_paysim_man.merge(df_fechas, on='step', how='left')
df_paysim_man.head(20)

step      type     amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0      1   PAYMENT    9839.64  C1231006815      170136.00       160296.36   
1      1   PAYMENT    1864.28  C1666544295       21249.00        19384.72   
2      1  TRANSFER     181.00  C1305486145         181.00            0.00   
3      1  CASH_OUT     181.00   C840083671         181.00            0.00   
4      1   PAYMENT   11668.14  C2048537720       41554.00        29885.86   
5      1   PAYMENT    7817.71    C90045638       53860.00        46042.29   
6      1   PAYMENT    7107.77   C154988899      183195.00       176087.23   
7      1   PAYMENT    7861.64  C1912850431      176087.23       168225.59   
8      1   PAYMENT    4024.36  C1265012928        2671.00            0.00   
9      1     DEBIT    5337.77   C712410124       41720.00        36382.23   
10     1     DEBIT    9644.94  C1900366749        4465.00            0.00   
11     1   PAYMENT    3099.97   C249177573       20771.00        17671.03   
12     1   PAYMENT    2560.74  C1648232591        5070.00         2509.26   
13     1   PAYMENT   11633.76  C1716932897       10127.00            0.00   
14     1   PAYMENT    4098.78  C1026483832      503264.00       499165.22   
15     1  CASH_OUT  229133.94   C905080434       15325.00            0.00   
16     1   PAYMENT    1563.82   C761750706         450.00            0.00   
17     1   PAYMENT    1157.86  C1237762639       21156.00        19998.14   
18     1   PAYMENT     671.64  C2033524545       15123.00        14451.36   
19     1  TRANSFER  215310.30  C1670993182         705.00            0.00   

       nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  \
0   M1979787155             0.0            0.00        0               0   
1   M2044282225             0.0            0.00        0               0   
2    C553264065             0.0            0.00        1               0   
3     C38997010         21182.0            0.00        1               0   
4   M1230701703             0.0            0.00        0               0   
5    M573487274             0.0            0.00        0               0   
6    M408069119             0.0            0.00        0               0   
7    M633326333             0.0            0.00        0               0   
8   M1176932104             0.0            0.00        0               0   
9    C195600860         41898.0        40348.79        0               0   
10   C997608398         10845.0       157982.12        0               0   
11  M2096539129             0.0            0.00        0               0   
12   M972865270             0.0            0.00        0               0   
13   M801569151             0.0            0.00        0               0   
14  M1635378213             0.0            0.00        0               0   
15   C476402209          5083.0        51513.44        0               0   
16  M1731217984             0.0            0.00        0               0   
17  M1877062907             0.0            0.00        0               0   
18   M473053293             0.0            0.00        0               0   
19  C1100439041         22425.0            0.00        0               0   

        fecha  
0  2023-09-19  
1  2023-09-19  
2  2023-09-19  
3  2023-09-19  
4  2023-09-19  
5  2023-09-19  
6  2023-09-19  
7  2023-09-19  
8  2023-09-19  
9  2023-09-19  
10 2023-09-19  
11 2023-09-19  
12 2023-09-19  
13 2023-09-19  
14 2023-09-19  
15 2023-09-19  
16 2023-09-19  
17 2023-09-19  
18 2023-09-19  
19 2023-09-19

In [67]:
df_paysim_man.groupby('type')['amount'].sum()

type
CASH_IN     2.363674e+11
CASH_OUT    3.944130e+11
DEBIT       2.271992e+08
PAYMENT     2.809337e+10
TRANSFER    4.852920e+11
Name: amount, dtype: float64

In [68]:
df_paysim_man.groupby('type')['type'].value_counts()

type
CASH_IN     1399284
CASH_OUT    2237500
DEBIT         41432
PAYMENT     2151495
TRANSFER     532909
Name: count, dtype: int64

In [69]:
df_paysim_man.describe()

step        amount  oldbalanceOrg  newbalanceOrig  \
count  6.362620e+06  6.362620e+06   6.362620e+06    6.362620e+06   
mean   2.433972e+02  1.798619e+05   8.338831e+05    8.551137e+05   
min    1.000000e+00  0.000000e+00   0.000000e+00    0.000000e+00   
25%    1.560000e+02  1.338957e+04   0.000000e+00    0.000000e+00   
50%    2.390000e+02  7.487194e+04   1.420800e+04    0.000000e+00   
75%    3.350000e+02  2.087215e+05   1.073152e+05    1.442584e+05   
max    7.430000e+02  9.244552e+07   5.958504e+07    4.958504e+07   
std    1.423320e+02  6.038582e+05   2.888243e+06    2.924049e+06   

       oldbalanceDest  newbalanceDest       isFraud  isFlaggedFraud  \
count    6.362620e+06    6.362620e+06  6.362620e+06    6.362620e+06   
mean     1.100702e+06    1.224996e+06  1.290820e-03    2.514687e-06   
min      0.000000e+00    0.000000e+00  0.000000e+00    0.000000e+00   
25%      0.000000e+00    0.000000e+00  0.000000e+00    0.000000e+00   
50%      1.327057e+05    2.146614e+05  0.000000e+00    0.000000e+00   
75%      9.430367e+05    1.111909e+06  0.000000e+00    0.000000e+00   
max      3.560159e+08    3.561793e+08  1.000000e+00    1.000000e+00   
std      3.399180e+06    3.674129e+06  3.590480e-02    1.585775e-03   

                               fecha  
count                        6362620  
mean   2024-05-18 09:32:02.022565120  
min              2023-09-19 00:00:00  
25%              2024-02-21 00:00:00  
50%              2024-05-14 00:00:00  
75%              2024-08-18 00:00:00  
max              2025-09-30 00:00:00  
std                              NaN

### <font color='#FCB53B'>**Clasificación de transacciones**</font>

Para poder asignar las transacciones a los clientes del **DataFrame de Churn**, se buscará hacer una clusterización teniendo el cuenta algunas características del presente dataset para conseguir patrones sintéticos pero lógicos, cercanos a la realidad.

#### <font color='#FDD2A9'>**Amount**</font>

Se tomarán los Cuartiles 1 y 3 (Q1 y Q3) de los montos correspondientes a cada tipo de transacción, y con esto se evaluará si cada transacción corresponde a un monto Bajo, Medio o Alto *(Low, Medium, High)* dentro de dicha categoría *(type)*

In [70]:
percentiles_amount = df_paysim_man.groupby('type')['amount'].quantile([0.25, 0.75]).unstack()
percentiles_amount

0.25         0.75
type                              
CASH_IN    70510.1825  239899.0875
CASH_OUT   72669.6500  246539.4775
DEBIT       1500.1800    5479.1750
PAYMENT     4383.8200   17561.2200
TRANSFER  215905.3500  974958.0000

In [71]:
df_paysim_man['amount_q1'] = df_paysim_man['type'].map(percentiles_amount[0.25])
df_paysim_man['amount_q3'] = df_paysim_man['type'].map(percentiles_amount[0.75])

In [72]:
conditions = [
    df_paysim_man['amount'] < df_paysim_man['amount_q1'],
    df_paysim_man['amount'] < df_paysim_man['amount_q3']
]

options = ['Low', 'Medium']

df_paysim_man['amount_label'] = np.select(conditions, options, default='High')

In [73]:
df_paysim_man.sample(20)

step      type      amount     nameOrig  oldbalanceOrg  \
3450472   257   PAYMENT     7849.75   C339797211        5363.00   
3347459   253   PAYMENT    19022.83  C1411139587           0.00   
5230048   371  CASH_OUT   167917.94   C717036156       81367.00   
5937841   404  CASH_OUT   193835.64   C507426596       33598.00   
5479248   379  CASH_OUT   166147.34  C1590841148           0.00   
114326     11   CASH_IN    83617.01  C1062789861     3923259.93   
4545954   326  CASH_OUT   284952.87  C1054628926        1114.00   
3660276   275   PAYMENT      372.50  C1521985469      199576.41   
3278752   251   PAYMENT    20920.66   C513402379       41659.00   
3647405   275   PAYMENT     9242.22   C257061403       10090.00   
2017279   180  CASH_OUT     5858.70   C677713816       16922.00   
578150     33   PAYMENT    19936.14   C391494424       20650.00   
1044590    94  CASH_OUT   167446.70  C1627446259       21421.00   
4196646   305   PAYMENT    58476.40   C866010578      109879.00   
2699943   211   PAYMENT      399.08   C236881010           0.00   
5560169   384   PAYMENT    10085.94  C2095965167           0.00   
763136     38  TRANSFER  1277607.35  C1198038726      101181.00   
5735169   399  CASH_OUT   348252.57  C1412851217         226.00   
3906709   284  CASH_OUT    23098.55  C1312025111        9222.00   
1029270    48   PAYMENT     9547.14  C2069817017       50049.00   

         newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
3450472            0.00   M790879080            0.00            0.00        0   
3347459            0.00   M499385920            0.00            0.00        0   
5230048            0.00  C1565077412       984788.67      1152706.61        0   
5937841            0.00   C505356613            0.00       193835.64        0   
5479248            0.00  C1266475869       204756.48       370903.81        0   
114326       4006876.94  C1090594488       749764.13       666147.12        0   
4545954            0.00   C580852750            0.00       284952.87        0   
3660276       199203.91    M16599489            0.00            0.00        0   
3278752        20738.34  M1496568861            0.00            0.00        0   
3647405          847.78   M591408859            0.00            0.00        0   
2017279        11063.30   C837145812        47466.61        53325.31        0   
578150           713.86  M1902044793            0.00            0.00        0   
1044590            0.00  C1046133601       816444.77       983891.47        0   
4196646        51402.60   M880036401            0.00            0.00        0   
2699943            0.00  M1756213283            0.00            0.00        0   
5560169            0.00   M454835640            0.00            0.00        0   
763136             0.00    C63559693        81245.34      1358852.69        0   
5735169            0.00  C2022580839        75662.00       423914.57        0   
3906709            0.00   C571094197       133411.54       156510.09        0   
1029270        40501.86   M403578035            0.00            0.00        0   

         isFlaggedFraud      fecha    amount_q1    amount_q3 amount_label  
3450472               0 2024-06-01    4383.8200   17561.2200       Medium  
3347459               0 2024-05-28    4383.8200   17561.2200         High  
5230048               0 2024-09-23   72669.6500  246539.4775       Medium  
5937841               0 2024-10-26   72669.6500  246539.4775       Medium  
5479248               0 2024-10-01   72669.6500  246539.4775       Medium  
114326                0 2023-09-29   70510.1825  239899.0875       Medium  
4545954               0 2024-08-09   72669.6500  246539.4775         High  
3660276               0 2024-06-19    4383.8200   17561.2200          Low  
3278752               0 2024-05-26    4383.8200   17561.2200         High  
3647405               0 2024-06-19    4383.8200   17561.2200       Medium  
2017279               0 2024-03-16   72669.6500  246539.4775   

#### <font color='#FDD2A9'>**Frequency**</font>

Para la **Frecuencia** se tomará la proporcion de cada tipo de transacción en la totalidad del dataset, y a partir de la presencia de cada una se determinará si es de Baja, Media o Alta *(Low, Medium, High)* Frecuecia

In [74]:
frecuencia_tipo = df_paysim_man['type'].value_counts(normalize=True)
frecuencia_tipo

type
CASH_OUT    0.351663
PAYMENT     0.338146
CASH_IN     0.219923
TRANSFER    0.083756
DEBIT       0.006512
Name: proportion, dtype: float64

In [75]:
df_paysim_man['type_freq'] = df_paysim_man['type'].map(frecuencia_tipo)

In [76]:
q1 = df_paysim_man['type_freq'].quantile(0.25)
q3 = df_paysim_man['type_freq'].quantile(0.75)

conditions = [
    df_paysim_man['type_freq'] < q1,
    df_paysim_man['type_freq'] < q3
]

choices = ['Low', 'Medium']

df_paysim_man['frequency_label'] = np.select(conditions, choices, default='High')

In [77]:
df_paysim_man.sample(5)

step      type     amount     nameOrig  oldbalanceOrg  \
5729187   399   PAYMENT   33600.87   C138258534      287865.72   
5835471   402   CASH_IN  286976.50  C1448702112     1056562.96   
141204     11  CASH_OUT  377490.01   C789183783      443112.00   
6345438   692  CASH_OUT  355087.48  C1023690858           0.00   
5766742   400   CASH_IN   44620.98  C1018223993     4070322.26   

         newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
5729187       254264.86  M1283258975            0.00            0.00        0   
5835471      1343539.46    C98675011       338463.51        51487.01        0   
141204         65621.99  C1264851251       657048.56      1527443.91        0   
6345438            0.00  C1862140046     10695611.64     11050699.13        0   
5766742      4114943.24  C1154425251       830784.04       786163.06        0   

         isFlaggedFraud      fecha   amount_q1    amount_q3 amount_label  \
5729187               0 2024-10-21   4383.8200   17561.2200         High   
5835471               0 2024-10-24  70510.1825  239899.0875         High   
141204                0 2023-09-29  72669.6500  246539.4775         High   
6345438               0 2025-08-10  72669.6500  246539.4775         High   
5766742               0 2024-10-22  70510.1825  239899.0875          Low   

         type_freq frequency_label  
5729187   0.338146          Medium  
5835471   0.219923          Medium  
141204    0.351663            High  
6345438   0.351663            High  
5766742   0.219923          Medium

In [78]:
map_scores = {'Low': 1, 'Medium': 2, 'High': 3}

df_paysim_man['amount_score'] = df_paysim_man['amount_label'].map(map_scores)
df_paysim_man['freq_score'] = df_paysim_man['frequency_label'].map(map_scores)

df_paysim_man['tran_score'] = df_paysim_man['amount_score'] + df_paysim_man['freq_score']

In [79]:
df_paysim_man['tran_score'].unique()

array([4, 3, 2, 5, 6], dtype=int64)

In [80]:
df_paysim_man.groupby('tran_score')['tran_score'].value_counts()

tran_score
2     143585
3    1174864
4    2478350
5    2006446
6     559375
Name: count, dtype: int64

### Nota:
---
Ahora, debido a que sólo menos del 10% de clientes corresponde a clientes VIP **(816/10000)**. Se clasificarán las transacciones como Bajas, Medias, Altas y VIP, dejando para esta última etiqueta solo el 10% de las transacciones con score continuo más alto

In [81]:
# Se crea un score continuo utilizando el score del monto de la transacción, el score de la frecuencia del tipo de transacción
# y además se tomará en cuenta el monto relativo de la transacción 
df_paysim_man['tran_score_cont'] = (
    df_paysim_man['amount_score']*0.7 + 
    df_paysim_man['freq_score']*0.3 + 
    df_paysim_man['amount'] / df_paysim_man['amount'].max() * 0.1
)


# Calcular cortes por cuantiles 33%, 60%, 90%
q33, q60, q90 = df_paysim_man['tran_score_cont'].quantile([0.33, 0.60, 0.90])
print(q33, q60, q90)

# Aplicar los labels de acuerdo a los bins
df_paysim_man['tran_label'] = pd.cut(
    df_paysim_man['tran_score_cont'],
    bins=[-np.inf, q33, q60, q90, np.inf],
    labels=['Low', 'Medium', 'High', 'VIP']
)

# Ver distribución
print(df_paysim_man['tran_label'].value_counts(normalize=False))
print(df_paysim_man['tran_label'].value_counts(normalize=True))

2.0000068410269423 2.3001011335404873 2.7004358974503537
tran_label
Low       2099665
High      1908786
Medium    1717907
VIP        636262
Name: count, dtype: int64
tran_label
Low       0.33
High      0.30
Medium    0.27
VIP       0.10
Name: proportion, dtype: float64


### <font color='#FCB53B'>**Asignación de transacciones**</font>

A continuación, utilizando las etiquetas de ambos datasets, se asignarán las transacciones de manera aleatoria, pero respetando ciertas proporciones que reflejen la realidad.

**Nota:**

Las siguients proporciones fueron asignadas a mano, buscando una distribución lógica entre los distintos tipos de clientes y transacciones y como debería ser el comportamiento de estos.

#### **Las siguients tablas se utilizarán como patrones a seguir en la asignación de transacciones a los clientes**

**Guía**

| Etiqueta	                  |	Número de transacciones	 |
|-----------------------------|--------------------------|
| VIP	                      | Alta	                 |
| Valioso - Bajo compromiso   | Media	                 |
| Standard              	  | Media	                 |
| Clientes potenciales	      | Baja	                 |
| Nuevos - Poco Valor         | Baja	                 |

**Transacciones**

| Tran Label  | Proporción |
|-------------|------------|
| Low         | 0.33       |
| High        | 0.30       |
| Medium      | 0.27       |
| VIP         | 0.10       |

**Distribución Transacciones**

| Cliente Label / Tran Label | Low           | Medium          | High         | Vip        | Total      |
|----------------------------|---------------|-----------------|--------------|------------|------------|
| Nuevos - Poco Valor        | 10%           | 3%              | 1%           | 0%         | 14%        |
| Clientes potenciales       | 8%            | 8%              | 3%           | 1%         | 20%        |
| Standard              	 | 6.5%          | 5%              | 7%           | 1%         | 19.5%      |
| Valioso - Bajo compromiso  | 7.5%          | 8%              | 4%           | 1%         | 20.5%      |
| VIP	                     | 1%            | 3%              | 15%          | 7%         | 26%        |
| Total                      | 33%           | 27%             | 30%          | 10%        | 100%       |

In [82]:
if 'df_alloc' in locals():
    del df_alloc

In [83]:
df_clients = df_churn_labeled.copy()
df_tx = df_paysim_man.copy()

In [84]:
# Tabla de distribución de transacciones
pct_table = {
 "Nuevos - Poco Valor":      [0.10, 0.03, 0.01, 0.00],
 "Clientes potenciales":     [0.08, 0.08, 0.03, 0.01],
 "Standard":                 [0.065,0.05, 0.07, 0.01],
 "Valioso - Bajo compromiso":[0.075,0.08, 0.04, 0.01],
 "VIP":                      [0.01, 0.03, 0.15, 0.07]
}
labels = ['Low','Medium','High','VIP']

In [85]:
total_tx = len(df_tx)
total_tx

6362620

In [86]:
# Cantidad de transacciones que se asignarán a cada tipo de cliente
cell_counts = {}
for cluster, probs in pct_table.items():
    counts = (np.array(probs) * total_tx).round().astype(int)
    cell_counts[cluster] = dict(zip(labels, counts))

cell_counts

{'Nuevos - Poco Valor': {'Low': 636262,
  'Medium': 190879,
  'High': 63626,
  'VIP': 0},
 'Clientes potenciales': {'Low': 509010,
  'Medium': 509010,
  'High': 190879,
  'VIP': 63626},
 'Standard': {'Low': 413570, 'Medium': 318131, 'High': 445383, 'VIP': 63626},
 'Valioso - Bajo compromiso': {'Low': 477196,
  'Medium': 509010,
  'High': 254505,
  'VIP': 63626},
 'VIP': {'Low': 63626, 'Medium': 190879, 'High': 954393, 'VIP': 445383}}

In [87]:
df_clients

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  ...  wealth_score  cluster_wealth  \
0          2       0.00              1  ...     40601.452             Low   
1          1   83807.86              1  ...     86981.762          Medium   
2          8  159660.80              3  ...    125453.228            High   
3          1       0.00              2  ...     37600.552             Low   
4          2  125510.82              1  ...     94474.050          Medium   
...      ...        ...            ...  ...           ...             ...   
9995       5       0.00              2  ...     38585.356             Low   
9996      10   57369.61              1  ...     69416.313          Medium   
9997       7       0.00              1  ...     16905.132             Low   
9998       3   75075.31              2  ...     74770.263          Medium   
9999       4  130142.79              1  ...     80426.907          Medium   

      engagement_score  cluster_engagement wealth_score_norm  \
0                  1.0                 Low          0.220009   
1                  0.8                 Low          0.471943   
2                  1.7                High          0.680918   
3                  1.0                 Low          0.203708   
4                  1.0                 Low          0.512641   
...                ...                 ...               ...   
9995               1.2              Medium          0.209058   
9996               1.0                 Low          0.376529   
9997               0.8                 Low          0.091292   
9998               1.2              Medium          0.405611   
9999               0.7                 Low          0.436338   

     engagement_score_norm  cluster_time_num final_score  cluster_final  \
0                     0.25               0.5    0.288004              2   
1                     0.15               0.5    0.348777              4   
2                     0.60               1.0    0.712367              3   
3                     0.25               0.0    0.181483              1   
4                     0.25               0.5    0.405056              4   
...                    ...               ...         ...            ...   
9995                  0.35               0.5    0.323623              2   
9996                  0.25               1.0    0.450612              0   
9997                  0.15               0.5    0.196517              1   
9998                  0.35               0.5    0.402245              4   
9999                  0.10               0.0    0.214535              1   

                  cluster_label  
0          Clientes potenciales  
1                      Standard  
2                           VIP  
3           Nuevos - Poco Valor  
4                      Standard  
...                         ...  
9995       Clientes potenciales  
9996  Valioso - Bajo compromiso  
9997        Nuevos - Poco Valor  
9998                   Standard  
9999        Nuevos - Poco Valor  

[10000 rows x 26 columns]

In [88]:
# Se crea una columna en el dataset de clientes que contabilizará la cantidad de transacciones asignadas a cada cliente
df_clients['n_assigned'] = 0

WEIGHTS_NOISE_SIGMA = 0.2 

tenure_max = df_clients['Tenure'].max()

for cluster, label_counts in cell_counts.items():
    clients_in_cluster = df_clients[df_clients['cluster_label'] == cluster].copy()
    n_clients = len(clients_in_cluster)
    if n_clients == 0:
        continue

    client_ids = clients_in_cluster['CustomerId'].values
    
    # Factor de peso dinámico en relación a la antigüedad del cliente
    tenure_factor = clients_in_cluster['Tenure'] / tenure_max

    # Ajuste según churn (clientes que se fueron menores probabilidades de obtener transacciones)
    weights = np.where(
        clients_in_cluster['Exited'] == 1,
        tenure_factor * 0.7,   # churn: menor peso (ejemplo: 70%)
        tenure_factor * 1.0    # activos: peso completo
    )
    

    # Generar un array de ruido para todas las ponderaciones
    noise_factor = np.random.normal(loc=1.0, scale=WEIGHTS_NOISE_SIGMA, size=len(weights))
    
    # Aplicar el ruido
    weights = weights * noise_factor
    
    # Opcional: asegurar que no haya pesos negativos
    weights = np.clip(weights, a_min=0.0001, a_max=None) 

    # Normalizamos para la distribución multinomial
    weights = weights / weights.sum()

    for label, count in label_counts.items():
        if count <= 0:
            continue

        allocated = np.random.multinomial(count, weights)
        tmp = pd.DataFrame({'CustomerId': client_ids, 'alloc': allocated})
        tmp = tmp[tmp['alloc'] > 0].copy()
        tmp['label'] = label

        if 'df_alloc' not in locals():
            df_alloc = tmp.copy()
        else:
            df_alloc = pd.concat([df_alloc, tmp], ignore_index=True)

In [89]:
df_alloc

CustomerId  alloc label
0        15701354     77   Low
1        15737173    345   Low
2        15788218   1262   Low
3        15699309    320   Low
4        15717426    918   Low
...           ...    ...   ...
37055    15735078    102   VIP
37056    15603794    337   VIP
37057    15587133    860   VIP
37058    15666295     65   VIP
37059    15703563    818   VIP

[37060 rows x 3 columns]

In [90]:
# Explotar la cantidad de transacciones para cada cliente en un dataframe que contenga 1 fila por transacción
rows = []
for r in df_alloc.itertuples(index=False):
    # Vectorizar repeticiones
    rows.append(pd.DataFrame({
        'CustomerId': np.repeat(r.CustomerId, r.alloc),
        'tran_label': np.repeat(r.label, r.alloc)
    }))
assignments = pd.concat(rows, ignore_index=True)

In [91]:
assignments['tran_label'].value_counts()

tran_label
Low       2099664
High      1908786
Medium    1717909
VIP        636261
Name: count, dtype: int64

In [92]:
assignments['tran_label'].value_counts(normalize=True)

tran_label
Low       0.33
High      0.30
Medium    0.27
VIP       0.10
Name: proportion, dtype: float64

In [93]:
proportions = df_tx['tran_label'].value_counts(normalize=True)
proportions

tran_label
Low       0.33
High      0.30
Medium    0.27
VIP       0.10
Name: proportion, dtype: float64

In [94]:
labels = ['Low', 'High', 'Medium', 'VIP']
num_transactions = {}
for label, proportion in zip(labels, proportions):
    num_transactions[label] = round(total_tx * proportion )

In [95]:
num_transactions

{'Low': 2099665, 'High': 1908786, 'Medium': 1717907, 'VIP': 636262}

### Nota:
---
Hay un pequeño desfase en la cantidad de transacciones debido a operaciones de redondeo:

* **Medium** +2<br>
* **VIP** -1<br>
* **Low** -1

Como 2 transacciones en una distribución de más de 600000 transacciones como mínimo no harán diferencia, las solucionaré manualmente.

In [96]:
idx_low = assignments[assignments['tran_label'] == 'Medium'].sample(1, random_state=123456789).index


In [97]:
idx_low[0]

3898025

In [98]:
assignments.loc[idx_low[0], 'tran_label'] = 'Low'

In [99]:
idx_vip = assignments[assignments['tran_label'] == 'Medium'].sample(1, random_state=987654321).index

In [100]:
assignments.loc[idx_vip[0], 'tran_label'] = 'VIP'

In [101]:
num_transactions

{'Low': 2099665, 'High': 1908786, 'Medium': 1717907, 'VIP': 636262}

In [102]:
assignments['tran_label'].value_counts()

tran_label
Low       2099665
High      1908786
Medium    1717907
VIP        636262
Name: count, dtype: int64

In [103]:
assignments['tran_label'].value_counts(normalize=True)

tran_label
Low       0.33
High      0.30
Medium    0.27
VIP       0.10
Name: proportion, dtype: float64

In [104]:
df_tx['tran_label'].value_counts(normalize=True)

tran_label
Low       0.33
High      0.30
Medium    0.27
VIP       0.10
Name: proportion, dtype: float64

In [105]:
# Por cada fila (cliente, label) debemos tomar del pool df_tx una transacción con ese label
# Para eficiencia: shuffle df_tx por label and asignar secuencialmente
df_tx = df_tx.sample(frac=1, random_state=42).reset_index(drop=True)  # shuffle
tx_pools = {lab: grp.reset_index(drop=True) for lab, grp in df_tx.groupby('tran_label')}

In [106]:
# Crear el mapeo: iterar en labels y asignar los slices
assigned_records = []

for label, pool in tx_pools.items():
    # Contabilizar la cantidad de registros necesarios para cada tipo de transacción
    needed = (assignments['tran_label']==label).sum()
    # Verificar que existen suficientes registros
    if needed > len(pool):
        raise ValueError(f"Not enough tx in pool for label {label}: need {needed}, have {len(pool)}")
    # Tomar la cantidad de filas necesarias
    pool_slice = pool.iloc[:needed].copy().reset_index(drop=True)
    # Obtener los clientes asignados al label 
    clients = assignments[assignments['tran_label']==label]['CustomerId'].values
    # Asignar los CustomerId al slice
    pool_slice['CustomerId'] = clients
    assigned_records.append(pool_slice)

In [107]:
df_assigned = pd.concat(assigned_records, ignore_index=True)

In [108]:
df_assigned

step      type     amount     nameOrig  oldbalanceOrg  \
0         259   PAYMENT     915.13  C2002954533            0.0   
1         188  CASH_OUT   20603.87   C813757373            0.0   
2         139  CASH_OUT   58605.72  C1850864812            0.0   
3         230   PAYMENT    4865.11   C886849972            0.0   
4         302  CASH_OUT   51042.59   C122114408          184.0   
...       ...       ...        ...          ...            ...   
6362615   255  CASH_OUT  288477.80   C179114770            0.0   
6362616   251  CASH_OUT  266104.05   C968963698        11142.0   
6362617   162  CASH_OUT  568721.16  C1050649224        10579.0   
6362618   184  CASH_OUT  262813.04  C1531821655       110591.0   
6362619   131  CASH_OUT  277421.94  C1416595543            0.0   

         newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
0                   0.0   M290849763            0.00            0.00        0   
1                   0.0   C823291717       558068.66       578672.53        0   
2                   0.0   C618657299       585494.94       644100.66        0   
3                   0.0   M623175144            0.00            0.00        0   
4                   0.0   C705120650       380143.14       431185.74        0   
...                 ...          ...             ...             ...      ...   
6362615             0.0   C319557527      1675070.28      1963548.09        0   
6362616             0.0  C1760225299       103740.54       369844.60        0   
6362617             0.0  C1021914317        67222.45       635943.61        0   
6362618             0.0   C737117988       321179.93       583992.97        0   
6362619             0.0   C915079452       291674.87       569096.81        0   

         ...    amount_q3 amount_label  type_freq  frequency_label  \
0        ...   17561.2200          Low   0.338146           Medium   
1        ...  246539.4775          Low   0.351663             High   
2        ...  246539.4775          Low   0.351663             High   
3        ...   17561.2200       Medium   0.338146           Medium   
4        ...  246539.4775          Low   0.351663             High   
...      ...          ...          ...        ...              ...   
6362615  ...  246539.4775         High   0.351663             High   
6362616  ...  246539.4775         High   0.351663             High   
6362617  ...  246539.4775         High   0.351663             High   
6362618  ...  246539.4775         High   0.351663             High   
6362619  ...  246539.4775         High   0.351663             High   

        amount_score  freq_score tran_score  tran_score_cont  tran_label  \
0                  1           2          3         1.300001         Low   
1                  1           3          4         1.600022         Low   
2                  1           3          4         1.600063         Low   
3                  2           2          4         2.000005         Low   
4                  1           3          4         1.600055         Low   
...              ...         ...        ...              ...         ...   
6362615            3           3          6         3.000312         VIP   
6362616            3           3          6         3.000288         VIP   
6362617            3           3          6         3.000615         VIP   
6362618            3           3          6         3.000284         VIP   
6362619            3           3          6         3.000300         VIP   

         CustomerId  
0          15701354  
1          15701354  
2          15701354  
3          15701354  
4          15701354  
...             ...  
6362615    15703563  
6362616    15703563  
6362617    15703563  
6362618    15703563  
6362619    15703563  

[6362620 rows x 23 columns]

In [110]:
df_assigned.columns

Index(['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
       'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud',
       'isFlaggedFraud', 'fecha', 'amount_q1', 'amount_q3', 'amount_label',
       'type_freq', 'frequency_label', 'amount_score', 'freq_score',
       'tran_score', 'tran_score_cont', 'tran_label', 'CustomerId', 'date'],
      dtype='object')

In [111]:
# Asignar fechas según churn/no-churn
# Lista con las fechas
all_dates = pd.date_range(start_date, end_date, freq='D')

# Preparar diccionarios con los clientes que abandonaron
client_abandon = df_clients.set_index('CustomerId')['ExitDate'].to_dict()
client_exited  = df_clients.set_index('CustomerId')['Exited'].to_dict()

# --- NUEVOS PARÁMETROS PARA AJUSTAR EL REALISMO ---
# Proporción de churners que se van "de repente" sin mostrar señales de decadencia.
prob_churn_repentino = 0.20  # 20% de los churners se comportarán como no-churners.

# Probabilidad relativa de transacción antes/después para los churners que SÍ muestran decadencia.
prob_antes_decadencia = 80
prob_despues_decadencia = 20

# --- FUNCIÓN CORREGIDA (VERSIÓN 2) ---
def sample_dates_for_client(n, cid):
    """
    Asigna fechas a 'n' transacciones para un cliente 'cid' con una lógica más realista.
    """
    exit_date = client_abandon.get(cid)
    
    # Caso 1: Cliente activo (no churner)
    if client_exited.get(cid, 0) == 0:
        # Actividad sesgada hacia el presente (pesos crecientes)
        weights = np.linspace(start=0.5, stop=1.5, num=len(all_dates))
        weights /= np.sum(weights)
        return np.random.choice(all_dates, size=n, replace=True, p=weights)
    
    # Caso 2: Cliente que hace churn
    else:
        if pd.isna(exit_date):
            return np.random.choice(all_dates, size=n, replace=True)

        # 2.1. Definir la ventana de fechas de actividad (SOLO hasta la fecha de salida)
        active_dates = all_dates[all_dates <= exit_date]
        if len(active_dates) == 0:
             return np.random.choice(all_dates, size=n, replace=True)

        # 2.2. Decidimos el comportamiento: Repentino o con Decadencia
        
        # CHURNER REPENTINO (20% de probabilidad)
        if np.random.rand() < prob_churn_repentino:
            # Se comporta como un cliente fiel, pero SÓLO hasta la ExitDate.
            # Su actividad es más probable en el tiempo reciente (pesos crecientes)
            weights = np.linspace(start=0.5, stop=1.5, num=len(active_dates))
            weights /= np.sum(weights)
            return np.random.choice(active_dates, size=n, replace=True, p=weights)
            
        # CHURNER CON DECADENCIA (80% de probabilidad)
        else:
            # Muestra decadencia (actividad sesgada al pasado, pesos decrecientes)
            weights = np.linspace(start=1.5, stop=0.5, num=len(active_dates))
            weights /= np.sum(weights)
            return np.random.choice(active_dates, size=n, replace=True, p=weights)

# --- El resto de la celda no cambia ---
# Asignación vectorizada de fechas
df_assigned['date'] = None
grouped = df_assigned.groupby('CustomerId').size().reset_index(name='n_tx')
for cid, n in grouped.values:
    dates = sample_dates_for_client(n, cid)
    df_assigned.loc[df_assigned['CustomerId']==cid, 'date'] = dates

In [ ]:
"""
# Asignar fechas según churn/no-churn
# Lista con las fechas
all_dates = pd.date_range(start_date, end_date, freq='D')

# Preparar diccionarios con los clientes que abandonaron
client_abandon = df_clients.set_index('CustomerId')['ExitDate'].to_dict()
client_exited  = df_clients.set_index('CustomerId')['Exited'].to_dict()

# Parametros exponenciales de descenso
half_life = 30.0
lam = np.log(2)/half_life

# Fución vectorizada para agregar samples por cliente
def sample_dates_for_client(n, cid):
    if client_exited.get(cid,0)==1 and not pd.isna(client_abandon.get(cid)):
        end = pd.to_datetime(client_abandon[cid]) - pd.Timedelta(days=1)
        start = end - pd.Timedelta(days=180)  # ventana de 6 meses
        rng_days = (end - start).days + 1
        if rng_days <= 0:
            # Volver a distribución uniforme antes de la última fecha
            choices = pd.date_range(start_date, end, freq='D')
            return np.random.choice(choices, size=n)
        # Probabilidades de descenso
        days = np.arange(rng_days)
        weights = np.exp(-lam*(rng_days-1 - days))
        weights = weights / weights.sum()
        choices = pd.date_range(start, end, freq='D')
        return np.random.choice(choices, size=n, p=weights)
    else:
        # Cliente activo uniforme en todas las fechas
        return np.random.choice(all_dates, size=n)

# Asignación vectorizada de fechas
df_assigned['date'] = None
grouped = df_assigned.groupby('CustomerId').size().reset_index(name='n_tx')
for cid, n in grouped.values:
    dates = sample_dates_for_client(n, cid)
    df_assigned.loc[df_assigned['CustomerId']==cid, 'date'] = dates
"""

### <font color='#FCB53B'>**Limpieza Datasets**</font>

***Se descartarán algunas de las columnas utilizadas para clusterización y asignación de transacciones para conservar datasets más livianos***

In [112]:
df_assigned['date'] = pd.to_datetime(df_assigned['date'])

In [113]:
df_tx_clean = df_assigned.copy()

In [114]:
df_tx_clean = df_tx_clean.drop(['step', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
                               'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud',
                               'isFlaggedFraud', 'fecha', 'amount_q1', 'amount_q3'], axis=1)

In [115]:
df_tx_clean.head()

type    amount amount_label  type_freq frequency_label  amount_score  \
0   PAYMENT    915.13          Low   0.338146          Medium             1   
1  CASH_OUT  20603.87          Low   0.351663            High             1   
2  CASH_OUT  58605.72          Low   0.351663            High             1   
3   PAYMENT   4865.11       Medium   0.338146          Medium             2   
4  CASH_OUT  51042.59          Low   0.351663            High             1   

   freq_score  tran_score  tran_score_cont tran_label  CustomerId       date  
0           2           3         1.300001        Low    15701354 2024-08-12  
1           3           4         1.600022        Low    15701354 2025-05-27  
2           3           4         1.600063        Low    15701354 2025-01-17  
3           2           4         2.000005        Low    15701354 2024-09-22  
4           3           4         1.600055        Low    15701354 2025-09-16

In [116]:
df_tx_clean.columns

Index(['type', 'amount', 'amount_label', 'type_freq', 'frequency_label',
       'amount_score', 'freq_score', 'tran_score', 'tran_score_cont',
       'tran_label', 'CustomerId', 'date'],
      dtype='object')

In [117]:
df_tx_col_order = ['date', 'CustomerId', 'type', 'amount', 'amount_label', 'type_freq', 'frequency_label',
                   'amount_score', 'freq_score', 'tran_score', 'tran_score_cont',
                   'tran_label']

In [118]:
df_tx_clean = df_tx_clean[df_tx_col_order].sort_values(by='date')

In [119]:
df_tx_clean.head()

date  CustomerId      type     amount amount_label  type_freq  \
3994159 2023-09-19    15643158  CASH_OUT  134289.36       Medium   0.351663   
164693  2023-09-19    15785078  CASH_OUT    3716.84          Low   0.351663   
5531185 2023-09-19    15649033   PAYMENT   61980.74         High   0.338146   
4610579 2023-09-19    15700383   PAYMENT   23338.41         High   0.338146   
3759739 2023-09-19    15761286  CASH_OUT   89888.35       Medium   0.351663   

        frequency_label  amount_score  freq_score  tran_score  \
3994159            High             2           3           5   
164693             High             1           3           4   
5531185          Medium             3           2           5   
4610579          Medium             3           2           5   
3759739            High             2           3           5   

         tran_score_cont tran_label  
3994159         2.300145       High  
164693          1.600004        Low  
5531185         2.700067       High  
4610579         2.700025       High  
3759739         2.300097     Medium

In [120]:
df_clients.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'ExitDate',
       'cluster_time', 'wealth_score', 'cluster_wealth', 'engagement_score',
       'cluster_engagement', 'wealth_score_norm', 'engagement_score_norm',
       'cluster_time_num', 'final_score', 'cluster_final', 'cluster_label',
       'n_assigned'],
      dtype='object')

In [121]:
df_clients_clean = df_clients.copy()

In [122]:
df_clients_clean = df_clients_clean.drop(['cluster_time', 'wealth_score', 'cluster_wealth', 'engagement_score',
                                           'cluster_engagement', 'wealth_score_norm', 'engagement_score_norm',
                                           'cluster_time_num', 'final_score', 'cluster_final','n_assigned'], 
                                         axis=1)

In [123]:
df_clients_clean

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited   ExitDate              cluster_label  
0           101348.88       1 2025-02-26       Clientes potenciales  
1           112542.58       0        NaT                   Standard  
2           113931.57       1 2024-07-23                        VIP  
3            93826.63       0        NaT        Nuevos - Poco Valor  
4            79084.10       0        NaT                   Standard  
...               ...     ...        ...                        ...  
9995         96270.64       0        NaT       Clientes potenciales  
9996        101699.77       0        NaT  Valioso - Bajo compromiso  
9997         42085.58       1 2025-05-16        Nuevos - Poco Valor  
9998         92888.52       1 2024-09-07                   Standard  
9999         38190.78       0        NaT        Nuevos - Poco Valor  

[10000 rows x 16 columns]

### <font color='#FCB53B'>**Escalado del monto de las transacciones**</font>

***Debido a que los datasets provienen de fuentes diferentes, para simular un escenario real de transacciones correspondientes a los clientes del banco (Dataset Churn), se escalarán los montos de las transacciones de acuerdo a las variables `Balance` y `EstimatedSalary` de dicho dataset***

In [124]:

# --------------------------
# Parámetros ajustables
# --------------------------
monetary_min = 1.0        # monto mínimo posible
monetary_max = df_clients_clean['EstimatedSalary'].max() * 0.7    # máximo razonable (ajustalo a lo que consideres realista)
clip_low_pct = 0.01       # recortar bottom 1% de amounts
clip_high_pct = 0.99      # recortar top 1% de amounts
eps = 1e-6

# --------------------------
# 0) Preparar clients: obtener EstimatedSalary por CustomerId
#    (si ya tienes max_tx_cap, lo recalculamos de forma robusta)
# --------------------------
clients = df_clients_clean[['CustomerId','EstimatedSalary','Balance']].drop_duplicates().set_index('CustomerId')

# 1) compresión de salario: log1p + min-max
clients['salary_log'] = np.log1p(clients['EstimatedSalary'].fillna(0.0))
scaler = MinMaxScaler()
clients['salary_norm'] = scaler.fit_transform(clients[['salary_log']])

# 2) mapear a rango monetario (cap por cliente)
clients['max_tx_cap'] = clients['salary_norm'] * (monetary_max - monetary_min) + monetary_min

# si querés dar algo de peso al balance, podrías usar:
# clients['max_tx_cap'] = 0.85*clients['max_tx_cap'] + 0.15*(clients['Balance'].clip(upper=monetary_max))

# 3) merge con df (si df ya contiene CustomerId)
df = df_tx_clean.merge(clients[['max_tx_cap']], left_on='CustomerId', right_index=True, how='left')

# 4) recortar amounts por percentiles para evitar outliers extremos
q_low, q_high = df['amount'].quantile([clip_low_pct, clip_high_pct])
df['amount_clipped'] = df['amount'].clip(lower=q_low, upper=q_high)

# 5) normalizar clipped amount a rango 0..1 (si q_high==q_low proteger)
den = (q_high - q_low) if (q_high - q_low) > 0 else eps
df['amount_ratio'] = (df['amount_clipped'] - q_low) / den
df['amount_ratio'] = df['amount_ratio'].clip(0,1)

# 6) calcular amount_scaled
df['amount_scaled'] = (df['amount_ratio'] * df['max_tx_cap']).clip(lower=monetary_min).round(2)

In [125]:
df['CustomerId'].nunique()

9636

In [126]:
df.describe()

date    CustomerId        amount  \
count                        6362620  6.362620e+06  6.362620e+06   
mean   2024-10-26 16:39:23.660253440  1.569024e+07  1.798619e+05   
min              2023-09-19 00:00:00  1.556570e+07  0.000000e+00   
25%              2024-05-02 00:00:00  1.562882e+07  1.338957e+04   
50%              2024-11-14 00:00:00  1.568951e+07  7.487194e+04   
75%              2025-05-01 00:00:00  1.575265e+07  2.087215e+05   
max              2025-09-30 00:00:00  1.581569e+07  9.244552e+07   
std                              NaN  7.142852e+04  6.038582e+05   

          type_freq  amount_score    freq_score    tran_score  \
count  6.362620e+06  6.362620e+06  6.362620e+06  6.362620e+06   
mean   2.934333e-01  2.000000e+00  2.261395e+00  4.261396e+00   
min    6.511783e-03  1.000000e+00  1.000000e+00  2.000000e+00   
25%    2.199226e-01  2.000000e+00  2.000000e+00  4.000000e+00   
50%    3.381461e-01  2.000000e+00  2.000000e+00  4.000000e+00   
75%    3.516633e-01  3.000000e+00  3.000000e+00  5.000000e+00   
max    3.516633e-01  3.000000e+00  3.000000e+00  6.000000e+00   
std    8.529494e-02  7.071067e-01  6.112314e-01  9.346676e-01   

       tran_score_cont    max_tx_cap  amount_clipped  amount_ratio  \
count     6.362620e+06  6.362620e+06    6.362620e+06  6.362620e+06   
mean      2.078613e+00  1.266249e+05    1.568259e+05  9.679578e-02   
min       1.000000e+00  1.000000e+00    4.494676e+02  0.000000e+00   
25%       1.700002e+00  1.215402e+05    1.338957e+04  8.009819e-03   
50%       2.000126e+00  1.312088e+05    7.487194e+04  4.606691e-02   
75%       2.400006e+00  1.365881e+05    2.087215e+05  1.289187e-01   
max       3.010817e+00  1.399947e+05    1.615979e+06  1.000000e+00   
std       5.279525e-01  1.421562e+04    2.433707e+05  1.506445e-01   

       amount_scaled  
count   6.362620e+06  
mean    1.242859e+04  
min     1.000000e+00  
25%     9.976375e+02  
50%     5.699055e+03  
75%     1.647973e+04  
max     1.399947e+05  
std     1.956878e+04

In [127]:
# Histograma simple de amount_scaled
plt.figure(figsize=(10,6))
plt.hist(df['amount_scaled'], bins=100, edgecolor='black', alpha=0.7)
plt.title("Distribución de Transacciones (amount_scaled)", fontsize=14)
plt.xlabel("Monto escalado")
plt.ylabel("Frecuencia")
plt.grid(axis='y', alpha=0.4)
plt.show()

In [128]:
df_tx_scaled = df.copy()

In [129]:
df_tx_scaled.columns

Index(['date', 'CustomerId', 'type', 'amount', 'amount_label', 'type_freq',
       'frequency_label', 'amount_score', 'freq_score', 'tran_score',
       'tran_score_cont', 'tran_label', 'max_tx_cap', 'amount_clipped',
       'amount_ratio', 'amount_scaled'],
      dtype='object')

# <font color='#315aa0'>**Salud del Dataset - Exploración**</font>

## <font color='#c37171'>**Chequeos Generales**</font>

In [ ]:
# Clientes
print("Clientes - info general:")
print(df_clients_clean.info())
print(df_clients_clean.describe())

# Transacciones
print("\nTransacciones - info general:")
print(df_tx_scaled.info())
print(df_tx_scaled.describe())

# Chequear duplicados
print("\nDuplicados clientes:", df_clients_clean.duplicated(subset=['CustomerId']).sum())
print("Duplicados transacciones:", df_tx_scaled.duplicated(subset=['CustomerId','date','amount']).sum())

# Chequear missing values
print("\nMissing en clientes:\n", df_clients_clean.isna().sum())
print("\nMissing en transacciones:\n", df_tx_scaled.isna().sum())

## <font color='#c37171'>**Distribuciones Numéricas**</font>

In [ ]:
# Definir colores
main_color = '#620c0c'
secondary = '#a14b4b'
kde_color = '#FDB860'

In [ ]:
numeric_cols_clients = ['CreditScore','Age','Tenure','Balance','NumOfProducts','HasCrCard','IsActiveMember','EstimatedSalary']
numeric_cols_tx = ['amount','amount_clipped','amount_ratio','amount_scaled']

# Histogramas clientes
plt.figure(figsize=(14,10))
for i,col in enumerate(numeric_cols_clients):
    plt.subplot(3,3,i+1)
    sns.histplot(df_clients_clean[col], bins=30, kde=True,
                 color=main_color,
                 line_kws={'color': kde_color, 'linewidth': 2})
    plt.title(col)
plt.tight_layout()
plt.savefig(os.path.join(IMG_PATH, "df_clients_numerical_dist.png"), dpi=300)
plt.show()

# Histogramas transacciones
plt.figure(figsize=(14,10))
for i,col in enumerate(numeric_cols_tx):
    plt.subplot(2,2,i+1)
    sns.histplot(df_tx_scaled[col], bins=50, kde=True,
                 color=main_color,
                 line_kws={'color': kde_color, 'linewidth': 2})
    plt.title(col)
plt.tight_layout()
plt.savefig(os.path.join(IMG_PATH, "df_tx_scaled_numerical_dist.png"), dpi=300)
plt.show()

# Boxplots
plt.figure(figsize=(14,6))
sns.boxplot(x='type', y='amount_scaled', data=df_tx_scaled, color=secondary)
plt.title("Boxplot amount_scaled por tipo de transacción")
plt.savefig(os.path.join(IMG_PATH, "df_tx_boxplots_amount_scaled.png"), dpi=300)
plt.show()

## <font color='#c37171'>**Churn**</font>

In [ ]:
# Pie chart distribución churn
churn_counts = df_clients_clean['Exited'].value_counts(normalize=True)

plt.figure(figsize=(6,6))
colors = [kde_color, main_color]  # Exited=0 → kde_color, Exited=1 → main_color
churn_counts.plot(kind='pie', autopct='%1.1f%%', startangle=90, colors=colors,
                  labels=['No Churn (0)', 'Churn (1)'])
plt.ylabel("")  # quitar etiqueta del eje
plt.title("Distribución de Churn")
plt.savefig(os.path.join(IMG_PATH, "churn_distribution_pie.png"), dpi=300)
plt.show()

## <font color='#c37171'>**Correlación**</font>

In [ ]:
corr_columns = numeric_cols_clients
corr_columns.append('Exited')
plt.figure(figsize=(10,8))
sns.heatmap(df_clients_clean[corr_columns].corr(), annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Correlación variables clientes")
plt.savefig(os.path.join(IMG_PATH, "corr_matrix.png"), dpi=300)
plt.show()

# Scatterplot
plt.figure(figsize=(8,6))
sns.scatterplot(x='EstimatedSalary', y='amount_scaled',
                data=df_clients_clean.merge(df_tx_scaled, on='CustomerId', how='right').sample(10000),
                color=main_color)
plt.title("Salary vs amount_scaled (sample 10k)")
plt.savefig(os.path.join(IMG_PATH, "scatter_salarios_transacciones.png"), dpi=300)
plt.show()

In [160]:
# Obtener los CustomerId únicos de df_tx
tx_ids = df_tx_scaled['CustomerId'].unique()

# Filtrar df_clients para quedarnos solo con los que tienen transacciones
df_clients_filtered = df_clients_clean[df_clients_clean['CustomerId'].isin(tx_ids)].copy()

# <font color='#315aa0'>**App Interaction Dataset Generation**</font>

In [ ]:
start_date

In [130]:
import numpy as np
import pandas as pd
from datetime import datetime
import uuid


# NOTA: Las variables 'start_date', 'end_date' y 'df_clients' deben estar definidas
# en su entorno (ej. en el notebook de Jupyte)

# reproducibilidad
RNG = np.random.default_rng(42)

# --- CONFIGURACIÓN GLOBAL DE RUIDO ---
# 1. Ruido en la Tasa Base (lambda)
# Introduce variabilidad individual en la actividad mensual de cada cliente fiel.
LAMBDA_NOISE_SIGMA = 0.20 # 20% de desviación estándar en la tasa media.

# 2. Ruido en el Decaimiento (Decay) de Churners
# Evita que la caída de actividad sea una línea perfectamente predecible.
DECAY_NOISE_SIGMA = 0.25 # 25% de desviación sobre el factor de decaimiento.

# 3. Ruido en Probabilidades de Evento (Transacciones/Push)
# Asegura que las probabilidades de acción (p_transfer, p_invest, etc.) varíen por sesión.
PROB_NOISE_SIGMA = 0.15 # 15% de desviación en las probabilidades de acción.

freq = "M"  # meses
# Nota: 'start_date' y 'end_date' deben estar disponibles.
try:
    months = pd.period_range(start=start_date, end=end_date, freq=freq).to_timestamp('M')
except NameError:
    # Usar valores de ejemplo si no están definidos
    print("Usando fechas de ejemplo. Defina 'start_date' y 'end_date'.")
    start_date = datetime(2022, 1, 1)
    end_date = datetime(2023, 12, 31)
    months = pd.period_range(start=start_date, end=end_date, freq=freq).to_timestamp('M')
    # Crear un df_clients mínimo si no está disponible para que el script corra
    try:
        if 'df_clients' not in locals():
            raise NameError
    except NameError:
        print("Definiendo 'df_clients' de ejemplo.")
        df_clients = pd.DataFrame({
            'CustomerId': [1001, 1002, 1003],
            'cluster_label': ['VIP', 'Standard', 'Nuevos - Poco Valor'],
            'Exited': [0, 1, 0],
            'ExitDate': [pd.NaT, datetime(2023, 10, 15), pd.NaT],
            'Tenure': [50, 20, 5]
        })

# nombres de clusters según tu df_clients
clusters = [
    "Nuevos - Poco Valor",
    "Clientes potenciales",
    "Standard",
    "Valioso - Bajo compromiso",
    "VIP"
]

# parámetros base por cluster (ejemplo; ajustalos)
cluster_params = {
    "Nuevos - Poco Valor": {
        "base_sessions_per_month": 1.5,
        "duration_mu": 2.0,  # log-normal mu
        "duration_sigma": 0.6,
        "p_transfer": 0.02,
        "p_payment": 0.05,
        "p_invest": 0.01,
        "p_push_open": 0.10,
        "p_failed_login": 0.01,
    },
    "Clientes potenciales": {
        "base_sessions_per_month": 3.0,
        "duration_mu": 2.3,
        "duration_sigma": 0.7,
        "p_transfer": 0.06,
        "p_payment": 0.08,
        "p_invest": 0.02,
        "p_push_open": 0.15,
        "p_failed_login": 0.02,
    },
    "Standard": {
        "base_sessions_per_month": 4.0,
        "duration_mu": 2.7,
        "duration_sigma": 0.8,
        "p_transfer": 0.10,
        "p_payment": 0.12,
        "p_invest": 0.03,
        "p_push_open": 0.18,
        "p_failed_login": 0.03,
    },
    "Valioso - Bajo compromiso": {
        "base_sessions_per_month": 3.5,
        "duration_mu": 2.6,
        "duration_sigma": 0.8,
        "p_transfer": 0.12,
        "p_payment": 0.10,
        "p_invest": 0.05,
        "p_push_open": 0.12,
        "p_failed_login": 0.02,
    },
    "VIP": {
        "base_sessions_per_month": 8.0,
        "duration_mu": 3.0,
        "duration_sigma": 0.9,
        "p_transfer": 0.25,
        "p_payment": 0.20,
        "p_invest": 0.15,
        "p_push_open": 0.35,
        "p_failed_login": 0.01,
    }
}


# --- PARÁMETROS DE CHURN (MANTENIDOS) ---
prob_churn_repentino_app = 0.20 # 20% de los churners se comportarán como no-churners.
last_n_months_decay = 6       # ventana de decadencia antes de exit
decay_final_frac = 0.05       # en la fecha de exit la actividad se reduce hasta este frac (5%)

# tenure weighting
tenure_max = df_clients['Tenure'].max()
tenure_weight = 0.5   # cuánto influye Tenure en la tasa (0..1)

# ---------- 1) Preparar base cliente x mes ----------
clients = df_clients[['CustomerId','cluster_label','Exited','ExitDate','Tenure']].copy()
clients['Tenure'] = clients['Tenure'].astype(float)

# crear cartesian product cliente x mes (vectorizado)
cust_ids = clients['CustomerId'].values
n_cust = len(cust_ids)
n_months = len(months)
# generamos DataFrame "grid" Cliente-Mes
grid = pd.DataFrame({
    'CustomerId': np.repeat(cust_ids, n_months),
    'month': np.tile(months.to_numpy(), n_cust)
})
# merge valores cliente
grid = grid.merge(clients, on='CustomerId', how='left')

churners_repentinos = (RNG.random(len(clients[clients['Exited'] == 1])) < prob_churn_repentino_app)
client_repentino_map = clients[clients['Exited'] == 1].set_index('CustomerId').assign(is_repentino=churners_repentinos)['is_repentino'].to_dict()

# --- FUNCIÓN CORREGIDA (VERSIÓN 3) - CON RUIDO INTRA-CLUSTER Y EN DECADENCIA ---
def compute_lambda_row(row):
    params = cluster_params.get(row['cluster_label'], cluster_params['Standard'])
    
    # 1. Calcular Lambda Base (Determinístico + Tenencia)
    base_lam = params['base_sessions_per_month']
    tenure_factor = (row['Tenure'] / tenure_max) * tenure_weight
    mean_lam = base_lam * (1 + tenure_factor)

    # 2. Añadir Ruido Intra-Cluster / Temporal (la variabilidad de un cliente fiel)
    # Esto evita que la media de un clúster sea una señal perfecta.
    # Usamos una semilla por fila para simular ruido temporal o individual no persistente.
    noise_factor_base = np.clip(
        RNG.normal(loc=1.0, scale=LAMBDA_NOISE_SIGMA),
        0.5, 2.0 # Limita el factor de variación a +/- 50-100% de la media
    )
    lam = mean_lam * noise_factor_base
    lam = max(0.01, lam) # Asegurar que lambda sea positivo

    # Caso Churner
    if row['Exited'] == 1 and pd.notna(row.get('ExitDate')):
        exit_date = pd.to_datetime(row['ExitDate'])
        
        # 1. Cliente que ya abandonó: lambda = 0
        month_end = row['month'] + pd.offsets.MonthEnd(0)
        if month_end >= exit_date:
            return 0.0
            
        # 2. Es un "Churner Repentino" (actividad como fiel, sin decadencia)
        is_repentino = client_repentino_map.get(row['CustomerId'], False)
        if is_repentino:
            # Devuelve 'lam' con el ruido base ya aplicado arriba
            return lam 
            
        # 3. Es un "Churner con Decadencia" (la mayoría)
        else:
            # Si el mes es anterior al de salida pero está en la ventana de decadencia, se reduce lambda.
            months_before = int(((exit_date.to_period('M') - row['month'].to_period('M')).n))
            
            if months_before <= last_n_months_decay and months_before > 0:
                # Decaimiento base lineal (el factor determinístico)
                frac = months_before / float(last_n_months_decay)
                base_decay_factor = (decay_final_frac + (1 - decay_final_frac) * frac)
                
                # Ruido de Decadencia: Evita que la caída sea una línea recta
                noise_decay_factor = np.clip(
                    RNG.normal(loc=1.0, scale=DECAY_NOISE_SIGMA),
                    0.5, 1.5 
                )
                
                # Aplicar el factor de decadencia (determinístico) y el ruido (aleatorio)
                lam = lam * base_decay_factor * noise_decay_factor 
                lam = max(0.01, lam) # Asegurar lambda positivo
                
    # Caso No-Churner (o Churner Repentino)
    return lam

# vectorizar compute_lambda_row con apply on grid
grid['lambda'] = grid.apply(compute_lambda_row, axis=1)

# ---------- 3) samplear número de sesiones por cliente-mes ----------
# usar Poisson
grid['n_sessions'] = RNG.poisson(grid['lambda'].values)

# eliminar filas con n_sessions == 0 para ahorrar memoria
grid = grid[grid['n_sessions'] > 0].reset_index(drop=True)

# ---------- 4) expandir a nivel de sesión (vectorizado) ----------
rep_counts = grid['n_sessions'].values
total_sessions = rep_counts.sum()
print(f"Total sesiones generadas: {total_sessions:,}")

session_customer = np.repeat(grid['CustomerId'].values, rep_counts)
session_month = np.repeat(grid['month'].values.astype('datetime64[ns]'), rep_counts)

# ---------- 5) generar propiedades por sesión (CON RUIDO EN PROBABILIDADES) ----------
# obtener cluster params per session by merging or mapping
cust_to_cluster = clients.set_index('CustomerId')['cluster_label'].to_dict()
session_cluster = np.vectorize(cust_to_cluster.get)(session_customer)

# durations: lognormal con parámetros por cluster
mu_map = {k: v['duration_mu'] for k,v in cluster_params.items()}
sigma_map = {k: v['duration_sigma'] for k,v in cluster_params.items()}
mu_arr = np.vectorize(mu_map.get)(session_cluster)
sigma_arr = np.vectorize(sigma_map.get)(session_cluster)

# sample duration in minutes
durations = RNG.lognormal(mean=mu_arr, sigma=sigma_arr)
# clip duration to reasonable bounds
durations = np.clip(durations, 0.5, 180.0)  # entre 30 segundos y 3 horas

# features per session: bernoulli with p depending on cluster
p_transfer_base = np.vectorize(lambda cl: cluster_params[cl]['p_transfer'])(session_cluster)
p_payment_base  = np.vectorize(lambda cl: cluster_params[cl]['p_payment'])(session_cluster)
p_invest_base   = np.vectorize(lambda cl: cluster_params[cl]['p_invest'])(session_cluster)
p_push_base     = np.vectorize(lambda cl: cluster_params[cl]['p_push_open'])(session_cluster)
p_fail_base     = np.vectorize(lambda cl: cluster_params[cl]['p_failed_login'])(session_cluster)

# Inyectar Ruido en las Probabilidades de Transacción/Evento
noise_factors = RNG.normal(loc=1.0, scale=PROB_NOISE_SIGMA, size=total_sessions)
noise_factors = np.clip(noise_factors, 0.5, 1.5) # Limitar la variación

# Aplicar ruido y asegurar que las probabilidades estén entre [0.001, 0.999]
p_transfer = np.clip(p_transfer_base * noise_factors, 0.001, 0.999)
p_payment  = np.clip(p_payment_base * noise_factors, 0.001, 0.999)
p_invest   = np.clip(p_invest_base * noise_factors, 0.001, 0.999)
p_push     = np.clip(p_push_base * noise_factors, 0.001, 0.999)
p_fail     = np.clip(p_fail_base * noise_factors, 0.001, 0.999)


# Muestreo con las probabilidades ruidosas
used_transfer = RNG.random(total_sessions) < p_transfer
used_payment  = RNG.random(total_sessions) < p_payment
used_invest   = RNG.random(total_sessions) < p_invest
opened_push   = RNG.random(total_sessions) < p_push
failed_login  = RNG.random(total_sessions) < p_fail

# session dates uniformly in month (vectorized)
month_starts = pd.to_datetime(session_month).to_period('M').to_timestamp()
month_ends = (pd.to_datetime(session_month).to_period('M') + 1).to_timestamp() - pd.Timedelta(days=1)
# sample integer days offset
days_in_month = (month_ends - month_starts).days + 1
rand_days = RNG.integers(0, days_in_month, size=total_sessions)
session_dates = month_starts + pd.to_timedelta(rand_days, unit='D')

# create session_id (uuid or simple incremental)
session_ids = np.arange(total_sessions).astype(str)

# assemble event-level DataFrame
df_sessions = pd.DataFrame({
    'session_id': session_ids,
    'CustomerId': session_customer,
    'cluster_label': session_cluster,
    'date': session_dates,
    'duration_min': durations,
    'used_transfer': used_transfer.astype(int),
    'used_payment': used_payment.astype(int),
    'used_invest': used_invest.astype(int),
    'opened_push': opened_push.astype(int),
    'failed_login': failed_login.astype(int)
})

# ---------- 6) Agregados por cliente (month-level) ----------
df_sessions['month'] = df_sessions['date'].dt.to_period('M').dt.to_timestamp()
agg = df_sessions.groupby(['CustomerId','month']).agg(
    num_sessions = ('session_id','count'),
    total_duration = ('duration_min','sum'),
    avg_session_duration = ('duration_min','mean'),
    pct_transfer = ('used_transfer','mean'),
    pct_payment  = ('used_payment','mean'),
    pct_invest   = ('used_invest','mean'),
    pct_push_open = ('opened_push','mean'),
    n_failed_logins = ('failed_login','sum'),
    last_session = ('date','max')
).reset_index()

# add days_since_last_login relative to global end_date
# Nota: 'end_date' debe ser el final del periodo de análisis
agg['days_since_last_login'] = (pd.to_datetime(end_date) - agg['last_session']).dt.days

# ---------- 7) Agregados por cliente global (features ML)
customer_features = agg.groupby('CustomerId').agg(
    total_sessions = ('num_sessions','sum'),
    mean_sessions_per_month = ('num_sessions','mean'),
    median_session_duration = ('avg_session_duration','median'),
    pct_sessions_with_transfer = ('pct_transfer','mean'),
    total_failed_logins = ('n_failed_logins','sum'),
    months_active = ('month','nunique'),
    last_session_date = ('last_session','max')
).reset_index()

# optional: merge back cluster and Exited
customer_features = customer_features.merge(df_clients[['CustomerId','cluster_label','Exited','Tenure']], on='CustomerId', how='left')

# ---------- 8) Validaciones (resumen rápido) ----------
print("\n--- Resumen de Datos Generados ---")
print(f"Sesiones totales: {len(df_sessions):,}")
print(f"Clientes con >=1 session: {customer_features.shape[0]:,}")
print("\nEstadísticas de 'total_sessions' por cluster:")
print(customer_features.groupby('cluster_label')['total_sessions'].describe(percentiles=[0.25,0.5,0.75]))

# Guardar
# df_sessions.to_parquet("app_sessions_noisy.parquet")
# customer_features.to_parquet("app_features_noisy.parquet")

Total sesiones generadas: 1,059,390

--- Resumen de Datos Generados ---
Sesiones totales: 1,059,390
Clientes con >=1 session: 9,981

Estadísticas de 'total_sessions' por cluster:
                            count        mean        std  min    25%    50%  \
cluster_label                                                                 
Clientes potenciales       2644.0   88.327156  18.612097  1.0   78.0   89.0   
Nuevos - Poco Valor        1431.0   43.198463   9.947823  1.0   38.0   43.0   
Standard                   2870.0  119.101394  26.567351  2.0  106.0  121.0   
VIP                         813.0  232.102091  61.590221  2.0  204.0  240.0   
Valioso - Bajo compromiso  2223.0  105.045434  24.711954  1.0   93.0  108.0   

                             75%    max  
cluster_label                            
Clientes potenciales       100.0  137.0  
Nuevos - Poco Valor         50.0   79.0  
Standard                   136.0  188.0  
VIP                        275.0  352.0  
Valioso - Bajo 

In [131]:
# NOTA: Asegúrate de que df_sessions y df_clients estén disponibles en este punto.

# 1. Calcular la fecha de la última sesión por cliente en df_sessions
# La columna de fecha en df_sessions es 'date'.
last_session_date = df_sessions.groupby('CustomerId')['date'].max().reset_index(name='LastSessionDate')

# 2. Filtrar clientes que abandonaron y unirlos con su última sesión
df_churned = df_clients[df_clients['Exited'] == 1].copy()
# Seleccionamos las columnas relevantes y realizamos el merge
df_churned_check = df_churned[['CustomerId', 'ExitDate', 'Exited']].merge(
    last_session_date, on='CustomerId', how='left'
)

# 3. Realizar la comprobación de integridad
# El error ocurre si la ExitDate es ANTES de la LastSessionDate.
df_churned_check['TemporalIntegrityError'] = df_churned_check['ExitDate'] < df_churned_check['LastSessionDate']

# 4. Reportar los casos problemáticos (donde el error es True)
integrity_violations = df_churned_check[df_churned_check['TemporalIntegrityError'] == True]

print(f"Clientes que abandonaron ('Exited'=1): {df_churned.shape[0]}")
print(f"Clientes con violación de integridad temporal: {integrity_violations.shape[0]}")

if integrity_violations.empty:
    print("\n✅ ¡Validación completada! No se encontraron sesiones después de las fechas de salida registradas.")
else:
    print("\n🚨 ¡ATENCIÓN! Se encontraron violaciones de integridad. Primeros 5 casos:")
    # Usamos .dt.date para imprimir las fechas de forma limpia
    violations_clean = integrity_violations[['CustomerId', 'ExitDate', 'LastSessionDate']].copy()
    violations_clean['ExitDate'] = violations_clean['ExitDate'].dt.date
    violations_clean['LastSessionDate'] = violations_clean['LastSessionDate'].dt.date
    
    print(violations_clean.head())
    print("\nEstas filas indican que el cliente tuvo actividad de sesión posterior a su fecha de salida ('ExitDate').")

Clientes que abandonaron ('Exited'=1): 2037
Clientes con violación de integridad temporal: 0

✅ ¡Validación completada! No se encontraron sesiones después de las fechas de salida registradas.


In [132]:
df_sessions

session_id  CustomerId         cluster_label       date  duration_min  \
0                0    15634602  Clientes potenciales 2023-09-29      6.474154   
1                1    15634602  Clientes potenciales 2023-09-16     17.387135   
2                2    15634602  Clientes potenciales 2023-09-07      8.424436   
3                3    15634602  Clientes potenciales 2023-09-05      4.650335   
4                4    15634602  Clientes potenciales 2023-10-15     20.289098   
...            ...         ...                   ...        ...           ...   
1059385    1059385    15628319   Nuevos - Poco Valor 2025-08-05      2.350522   
1059386    1059386    15628319   Nuevos - Poco Valor 2025-08-31      7.107165   
1059387    1059387    15628319   Nuevos - Poco Valor 2025-08-13      2.311738   
1059388    1059388    15628319   Nuevos - Poco Valor 2025-09-28      9.683400   
1059389    1059389    15628319   Nuevos - Poco Valor 2025-09-08      5.399559   

         used_transfer  used_payment  used_invest  opened_push  failed_login  \
0                    0             0            0            0             0   
1                    0             0            0            0             0   
2                    0             0            0            0             0   
3                    0             0            0            0             0   
4                    0             1            0            0             0   
...                ...           ...          ...          ...           ...   
1059385              0             0            0            0             0   
1059386              0             0            0            0             0   
1059387              0             0            0            0             0   
1059388              0             0            0            0             0   
1059389              0             0            0            0             0   

             month  
0       2023-09-01  
1       2023-09-01  
2       2023-09-01  
3       2023-09-01  
4       2023-10-01  
...            ...  
1059385 2025-08-01  
1059386 2025-08-01  
1059387 2025-08-01  
1059388 2025-09-01  
1059389 2025-09-01  

[1059390 rows x 11 columns]

In [133]:
customer_features

CustomerId  total_sessions  mean_sessions_per_month  \
0       15565701             113                 4.520000   
1       15565706              33                 1.833333   
2       15565714             109                 4.360000   
3       15565779             130                 5.652174   
4       15565796             142                 5.680000   
...          ...             ...                      ...   
9976    15815628             105                 4.375000   
9977    15815645             281                11.240000   
9978    15815656             237                11.285714   
9979    15815660              85                 3.541667   
9980    15815690             108                 4.320000   

      median_session_duration  pct_sessions_with_transfer  \
0                   18.043798                    0.100683   
1                    7.847351                    0.000000   
2                   20.580506                    0.138143   
3                   13.791449                    0.060197   
4                   17.602444                    0.084667   
...                       ...                         ...   
9976                11.526779                    0.056415   
9977                29.469579                    0.233503   
9978                29.198323                    0.253753   
9979                12.054533                    0.021230   
9980                18.717743                    0.109952   

      total_failed_logins  months_active last_session_date  \
0                       3             25        2025-09-30   
1                       0             18        2025-06-06   
2                       0             25        2025-09-19   
3                       1             23        2025-09-27   
4                       2             25        2025-09-30   
...                   ...            ...               ...   
9976                    2             24        2025-08-25   
9977                    3             25        2025-09-30   
9978                    2             21        2025-05-29   
9979                    1             24        2025-09-28   
9980                    6             25        2025-09-28   

                  cluster_label  Exited  Tenure  
0     Valioso - Bajo compromiso       0       9  
1           Nuevos - Poco Valor       1       1  
2                      Standard       0       1  
3          Clientes potenciales       0       6  
4                      Standard       0      10  
...                         ...     ...     ...  
9976       Clientes potenciales       0       8  
9977                        VIP       0       8  
9978                        VIP       1       9  
9979       Clientes potenciales       0       1  
9980                   Standard       0       3  

[9981 rows x 11 columns]

# <font color='#315aa0'>**Filtrado**</font>

In [146]:
tx_ids = df_tx_scaled['CustomerId'].nunique()


In [147]:
cl_ids = df_clients_clean['CustomerId'].nunique()


In [148]:
ss_ids = df_sessions['CustomerId'].nunique()


In [166]:
ids_count

{'clients': 10000, 'tx': 9636, 'ss_ids': 9981}

In [149]:
ids_count = {'clients': cl_ids,
             'tx': tx_ids,
             'ss_ids': ss_ids}

In [154]:
ids_array = {'clients': df_clients_clean['CustomerId'].unique(),
             'tx': df_tx_scaled['CustomerId'].unique(),
             'ss_ids': df_sessions['CustomerId'].unique()}

In [158]:
min_ids = 10001
for key, value in ids_count.items():
    if value < min_ids:
        min_ids = value
        ids_val = ids_array[key]

print(len(ids_val))
print(ids_val)

9636
[15643158 15785078 15649033 ... 15798824 15754342 15597394]


In [163]:
# Filtrar df_clients para quedarnos solo con los que tienen transacciones
df_clients_filtered = df_clients_filtered[df_clients_filtered['CustomerId'].isin(ids_val)].copy()
df_tx_filtered = df_tx_scaled[df_tx_scaled['CustomerId'].isin(ids_val)].copy()
df_sessions_filtered = df_sessions[df_sessions['CustomerId'].isin(ids_val)].copy()
customer_features_filtered = customer_features[customer_features['CustomerId'].isin(ids_val)].copy()

In [165]:
df_clients_filtered['CustomerId'].nunique(), df_tx_filtered['CustomerId'].nunique(), df_sessions_filtered['CustomerId'].nunique(), customer_features_filtered['CustomerId'].nunique()

(9636, 9636, 9617, 9617)

In [167]:
ids_val_2 = df_sessions_filtered['CustomerId'].unique()
df_clients_filtered = df_clients_filtered[df_clients_filtered['CustomerId'].isin(ids_val_2)].copy()
df_tx_filtered = df_tx_filtered[df_tx_scaled['CustomerId'].isin(ids_val_2)].copy()

In [168]:
df_clients_filtered['CustomerId'].nunique(), df_tx_filtered['CustomerId'].nunique(), df_sessions_filtered['CustomerId'].nunique(), customer_features_filtered['CustomerId'].nunique()

(9617, 9617, 9617, 9617)

# <font color='#315aa0'>**Guardado Datasets**</font>

In [169]:
df_clients_filtered.to_parquet(DATA_PATH/'clients.parquet', index=False)
df_tx_filtered.to_parquet(DATA_PATH/'transactions.parquet', index=False)
df_sessions_filtered.to_parquet(DATA_PATH/'app_sessions.parquet', index=False)
customer_features_filtered.to_parquet(DATA_PATH/'client_app_features.parquet', index=False)

In [170]:
df_clients_filtered

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited   ExitDate              cluster_label  
0           101348.88       1 2025-02-26       Clientes potenciales  
1           112542.58       0        NaT                   Standard  
2           113931.57       1 2024-07-23                        VIP  
3            93826.63       0        NaT        Nuevos - Poco Valor  
4            79084.10       0        NaT                   Standard  
...               ...     ...        ...                        ...  
9995         96270.64       0        NaT       Clientes potenciales  
9996        101699.77       0        NaT  Valioso - Bajo compromiso  
9997         42085.58       1 2025-05-16        Nuevos - Poco Valor  
9998         92888.52       1 2024-09-07                   Standard  
9999         38190.78       0        NaT        Nuevos - Poco Valor  

[9617 rows x 16 columns]