# Generated by Django 4.2 on 2025-10-26 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientFeature",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("CreditScore", models.FloatField(blank=True, null=True)),
                ("Geography", models.CharField(blank=True, max_length=50, null=True)),
                ("Gender", models.CharField(blank=True, max_length=20, null=True)),
                ("Age", models.FloatField(blank=True, null=True)),
                ("Tenure", models.FloatField(blank=True, null=True)),
                ("Balance", models.FloatField(blank=True, null=True)),
                ("NumOfProducts", models.FloatField(blank=True, null=True)),
                ("HasCrCard", models.IntegerField(blank=True, null=True)),
                ("IsActiveMember", models.IntegerField(blank=True, null=True)),
                ("EstimatedSalary", models.FloatField(blank=True, null=True)),
                ("avg_tx_amount", models.FloatField(blank=True, null=True)),
                ("std_tx_amount", models.FloatField(blank=True, null=True)),
                ("days_since_last_tx", models.FloatField(blank=True, null=True)),
                ("tx_q1q2_rate_of_change", models.FloatField(blank=True, null=True)),
                ("tx_q2q3_rate_of_change", models.FloatField(blank=True, null=True)),
                ("avg_ss_duration", models.FloatField(blank=True, null=True)),
                ("std_ss_duration", models.FloatField(blank=True, null=True)),
                ("days_since_last_ss", models.FloatField(blank=True, null=True)),
                ("ss_q1q2_rate_of_change", models.FloatField(blank=True, null=True)),
                ("ss_q2q3_rate_of_change", models.FloatField(blank=True, null=True)),
                ("failed_ratio_spike_q2", models.FloatField(blank=True, null=True)),
                ("failed_ratio_spike_q3", models.FloatField(blank=True, null=True)),
                ("failed_ratio_volatility", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "client_feature",
            },
        ),
        migrations.CreateModel(
            name="ChurnPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo", models.CharField(max_length=50)),
                ("prob_churn", models.FloatField()),
                ("data_execucao", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="cliente_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="predictions",
                        to="customers.clientfeature",
                    ),
                ),
            ],
            options={
                "db_table": "churn_predictions",
            },
        ),
    ]
