# Generated by Django 4.2 on 2025-10-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChurnPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo", models.CharField(max_length=50)),
                ("prob_churn", models.FloatField()),
                ("data_execucao", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "churn_predictions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ClientFeature",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("CreditScore", models.BigIntegerField(blank=True, null=True)),
                ("Age", models.BigIntegerField(blank=True, null=True)),
                ("Tenure", models.BigIntegerField(blank=True, null=True)),
                ("Balance", models.FloatField(blank=True, null=True)),
                ("NumOfProducts", models.BigIntegerField(blank=True, null=True)),
                ("HasCrCard", models.BigIntegerField(blank=True, null=True)),
                ("IsActiveMember", models.BigIntegerField(blank=True, null=True)),
                ("EstimatedSalary", models.FloatField(blank=True, null=True)),
                ("days_since_last_tx", models.BigIntegerField(blank=True, null=True)),
                ("txs_avg_amount", models.FloatField(blank=True, null=True)),
                ("amount_std", models.FloatField(blank=True, null=True)),
                ("avg_cashout_amount", models.FloatField(blank=True, null=True)),
                ("ratio_recent_vs_past_txs", models.FloatField(blank=True, null=True)),
                (
                    "ratio_recent_vs_past_amount",
                    models.FloatField(blank=True, null=True),
                ),
                ("ratio_cashouts", models.FloatField(blank=True, null=True)),
                ("ratio_transfers", models.FloatField(blank=True, null=True)),
                ("inflation_pressure", models.FloatField(blank=True, null=True)),
                ("days_since_last_ss", models.BigIntegerField(blank=True, null=True)),
                ("total_ss_past30d", models.BigIntegerField(blank=True, null=True)),
                ("total_ss_past90d", models.BigIntegerField(blank=True, null=True)),
                ("avg_ss_per_wk", models.FloatField(blank=True, null=True)),
                ("avg_ss_duration_min", models.FloatField(blank=True, null=True)),
                ("std_ss_duration_min", models.FloatField(blank=True, null=True)),
                (
                    "ratio_ss_time_recent_vs_past",
                    models.FloatField(blank=True, null=True),
                ),
                ("ratio_events_sessios", models.FloatField(blank=True, null=True)),
                ("ratio_failed_ss", models.FloatField(blank=True, null=True)),
                ("total_opened_push", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "client_feature",
                "managed": False,
            },
        ),
    ]
