# Generated by Django 4.2 on 2025-10-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientfeature",
            old_name="Age",
            new_name="age",
        ),
        migrations.RenameField(
            model_name="clientfeature",
            old_name="Balance",
            new_name="balance",
        ),
        migrations.RenameField(
            model_name="clientfeature",
            old_name="CreditScore",
            new_name="creditscore",
        ),
        migrations.RenameField(
            model_name="clientfeature",
            old_name="EstimatedSalary",
            new_name="estimatedsalary",
        ),
        migrations.RenameField(
            model_name="clientfeature",
            old_name="Gender",
            new_name="gender",
        ),
        migrations.RenameField(
            model_name="clientfeature",
            old_name="Geography",
            new_name="geography",
        ),
        migrations.RenameField(
            model_name="clientfeature",
            old_name="HasCrCard",
            new_name="hascrcard",
        ),
        migrations.RenameField(
            model_name="clientfeature",
            old_name="IsActiveMember",
            new_name="isactivemember",
        ),
        migrations.RenameField(
            model_name="clientfeature",
            old_name="NumOfProducts",
            new_name="numofproducts",
        ),
        migrations.RenameField(
            model_name="clientfeature",
            old_name="Tenure",
            new_name="tenure",
        ),
    ]
