# Generated by Django 4.2 on 2025-10-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_rename_age_clientfeature_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="churnprediction",
            name="riesgo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="churnprediction",
            name="modelo",
            field=models.CharField(max_length=100),
        ),
    ]
