# Generated by Django 4.2 on 2025-10-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_churnprediction_riesgo_alter_churnprediction_modelo"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientfeature",
            name="customerid",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="clientfeature",
            name="surname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
