# Generated by Django 4.2 on 2025-10-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_clientfeature_customerid_clientfeature_surname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientfeature",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="clientfeature",
            name="geography",
        ),
        migrations.AddField(
            model_name="clientfeature",
            name="gender_male",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientfeature",
            name="geography_germany",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientfeature",
            name="geography_spain",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
