# Generated by Django 4.2 on 2025-10-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_remove_clientfeature_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientfeature",
            name="hascrcard",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clientfeature",
            name="isactivemember",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
